package dev.optio.feature.widgets.tools

import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.Logout
import androidx.compose.material.icons.filled.Bolt
import androidx.compose.material.icons.filled.Cancel
import androidx.compose.material.icons.filled.ChatBubble
import androidx.compose.material.icons.filled.Check
import androidx.compose.material.icons.filled.CheckCircle
import androidx.compose.material.icons.filled.Dns
import androidx.compose.material.icons.filled.Feedback
import androidx.compose.material.icons.filled.LaptopMac
import androidx.compose.material.icons.filled.LibraryAdd
import androidx.compose.material.icons.filled.Memory
import androidx.compose.material.icons.filled.Notifications
import androidx.compose.material.icons.filled.PanTool
import androidx.compose.material.icons.filled.PlayArrow
import androidx.compose.material.icons.filled.Snooze
import androidx.compose.material.icons.filled.Terminal
import androidx.compose.material.icons.filled.Warning
import androidx.compose.material.icons.filled.WifiOff
import androidx.compose.material.icons.outlined.Bedtime
import androidx.compose.material.icons.outlined.Cancel
import androidx.compose.material.icons.outlined.CheckCircle
import androidx.compose.material.icons.outlined.PlayCircle
import androidx.compose.material.icons.outlined.Schedule
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathNode
import androidx.compose.ui.graphics.vector.VectorGroup
import androidx.compose.ui.graphics.vector.VectorPath
import dev.optio.core.ui.components.OptioIcons
import java.io.File
import org.junit.Assume.assumeTrue
import org.junit.Test

/**
 * Writes the widget / tile / shortcut glyphs as vector drawables from the Material icon set (and
 * the app's own bot mark), so the path data is the library's, not a hand transcription. Opt-in:
 *
 * ```
 * OPTIO_GENERATE_WIDGET_ICONS=1 ./gradlew :feature:widgets:testDebugUnitTest --tests '*WidgetIconGenerator*'
 * ```
 *
 * Every drawable is white (`#FFFFFFFF`) so a Glance `ColorFilter.tint`, a tile's icon tinting and
 * a shortcut's adaptive foreground all colour it. Git glyphs (branch, pull request) have no
 * Material equivalent and are drawn by hand in `res/drawable` (lucide, like the app icon).
 */
class WidgetIconGenerator {
    private val icons: Map<String, ImageVector> =
        mapOf(
            "widget_ic_hand" to Icons.Filled.PanTool,
            "widget_ic_bubble" to Icons.Filled.ChatBubble,
            "widget_ic_zzz" to Icons.Filled.Snooze,
            "widget_ic_bell" to Icons.Filled.Notifications,
            "widget_ic_check_filled" to Icons.Filled.CheckCircle,
            "widget_ic_alert_bubble" to Icons.Filled.Feedback,
            "widget_ic_triangle" to Icons.Filled.Warning,
            "widget_ic_x_filled" to Icons.Filled.Cancel,
            "widget_ic_x_outline" to Icons.Outlined.Cancel,
            "widget_ic_check_outline" to Icons.Outlined.CheckCircle,
            "widget_ic_clock" to Icons.Outlined.Schedule,
            "widget_ic_play" to Icons.Filled.PlayArrow,
            "widget_ic_play_circle" to Icons.Outlined.PlayCircle,
            "widget_ic_cpu" to Icons.Filled.Memory,
            "widget_ic_laptop" to Icons.Filled.LaptopMac,
            "widget_ic_server" to Icons.Filled.Dns,
            "widget_ic_terminal" to Icons.Filled.Terminal,
            "widget_ic_bolt" to Icons.Filled.Bolt,
            "widget_ic_exit" to Icons.AutoMirrored.Filled.Logout,
            "widget_ic_moon" to Icons.Outlined.Bedtime,
            "widget_ic_wifi_off" to Icons.Filled.WifiOff,
            "widget_ic_new_work" to Icons.Filled.LibraryAdd,
            "widget_ic_check" to Icons.Filled.Check,
            "widget_ic_bot" to OptioIcons.Bot,
        )

    @Test
    fun generate() {
        assumeTrue("set OPTIO_GENERATE_WIDGET_ICONS=1 to regenerate", System.getenv("OPTIO_GENERATE_WIDGET_ICONS") == "1")
        val dir = File("src/main/res/drawable").apply { mkdirs() }
        icons.forEach { (name, vector) -> File(dir, "$name.xml").writeText(vectorXml(vector)) }
    }

    private fun vectorXml(vector: ImageVector): String =
        buildString {
            appendLine("""<?xml version="1.0" encoding="utf-8"?>""")
            appendLine("<!-- Generated by WidgetIconGenerator from ${vector.name}. Do not edit. -->")
            appendLine("""<vector xmlns:android="http://schemas.android.com/apk/res/android"""")
            appendLine("""    android:width="${vector.defaultWidth.value.fmt()}dp"""")
            appendLine("""    android:height="${vector.defaultHeight.value.fmt()}dp"""")
            appendLine("""    android:viewportWidth="${vector.viewportWidth.fmt()}"""")
            append("""    android:viewportHeight="${vector.viewportHeight.fmt()}"""")
            appendLine(">")
            appendGroup(vector.root, "    ")
            appendLine("</vector>")
        }

    private fun StringBuilder.appendGroup(
        group: VectorGroup,
        indent: String,
    ) {
        for (node in group) {
            when (node) {
                is VectorPath -> appendPath(node, indent)
                is VectorGroup -> {
                    appendLine("$indent<group>")
                    appendGroup(node, "$indent    ")
                    appendLine("$indent</group>")
                }
            }
        }
    }

    private fun StringBuilder.appendPath(
        path: VectorPath,
        indent: String,
    ) {
        appendLine("$indent<path")
        if (path.fill is SolidColor) {
            appendLine("""$indent    android:fillColor="#FFFFFFFF"""")
            if (path.fillAlpha != 1f) appendLine("""$indent    android:fillAlpha="${path.fillAlpha.fmt()}"""")
        }
        if (path.stroke is SolidColor) {
            appendLine("""$indent    android:strokeColor="#FFFFFFFF"""")
            appendLine("""$indent    android:strokeWidth="${path.strokeLineWidth.fmt()}"""")
            if (path.strokeLineCap == StrokeCap.Round) appendLine("""$indent    android:strokeLineCap="round"""")
            if (path.strokeLineJoin == StrokeJoin.Round) appendLine("""$indent    android:strokeLineJoin="round"""")
        }
        if (path.pathFillType.toString() == "EvenOdd") appendLine("""$indent    android:fillType="evenOdd"""")
        appendLine("""$indent    android:pathData="${path.pathData.joinToString(" ") { it.svg() }}" />""")
    }

    private fun PathNode.svg(): String =
        when (this) {
            PathNode.Close -> "Z"
            is PathNode.MoveTo -> "M${x.fmt()},${y.fmt()}"
            is PathNode.RelativeMoveTo -> "m${dx.fmt()},${dy.fmt()}"
            is PathNode.LineTo -> "L${x.fmt()},${y.fmt()}"
            is PathNode.RelativeLineTo -> "l${dx.fmt()},${dy.fmt()}"
            is PathNode.HorizontalTo -> "H${x.fmt()}"
            is PathNode.RelativeHorizontalTo -> "h${dx.fmt()}"
            is PathNode.VerticalTo -> "V${y.fmt()}"
            is PathNode.RelativeVerticalTo -> "v${dy.fmt()}"
            is PathNode.CurveTo -> "C${x1.fmt()},${y1.fmt()} ${x2.fmt()},${y2.fmt()} ${x3.fmt()},${y3.fmt()}"
            is PathNode.RelativeCurveTo -> "c${dx1.fmt()},${dy1.fmt()} ${dx2.fmt()},${dy2.fmt()} ${dx3.fmt()},${dy3.fmt()}"
            is PathNode.ReflectiveCurveTo -> "S${x1.fmt()},${y1.fmt()} ${x2.fmt()},${y2.fmt()}"
            is PathNode.RelativeReflectiveCurveTo -> "s${dx1.fmt()},${dy1.fmt()} ${dx2.fmt()},${dy2.fmt()}"
            is PathNode.QuadTo -> "Q${x1.fmt()},${y1.fmt()} ${x2.fmt()},${y2.fmt()}"
            is PathNode.RelativeQuadTo -> "q${dx1.fmt()},${dy1.fmt()} ${dx2.fmt()},${dy2.fmt()}"
            is PathNode.ReflectiveQuadTo -> "T${x.fmt()},${y.fmt()}"
            is PathNode.RelativeReflectiveQuadTo -> "t${dx.fmt()},${dy.fmt()}"
            is PathNode.ArcTo ->
                "A${horizontalEllipseRadius.fmt()},${verticalEllipseRadius.fmt()} ${theta.fmt()} " +
                    "${if (isMoreThanHalf) 1 else 0},${if (isPositiveArc) 1 else 0} ${arcStartX.fmt()},${arcStartY.fmt()}"
            is PathNode.RelativeArcTo ->
                "a${horizontalEllipseRadius.fmt()},${verticalEllipseRadius.fmt()} ${theta.fmt()} " +
                    "${if (isMoreThanHalf) 1 else 0},${if (isPositiveArc) 1 else 0} ${arcStartDx.fmt()},${arcStartDy.fmt()}"
        }

    private fun Float.fmt(): String {
        val rounded = Math.round(this * 1000f) / 1000f
        return if (rounded == rounded.toLong().toFloat()) rounded.toLong().toString() else rounded.toString()
    }
}
