/**
 * gen-kotlin — emit Kotlin (kotlinx.serialization) models from the shared
 * TypeScript protocol types so the Android app (apps/android) and the server
 * share one wire format. The Kotlin twin of gen-swift.ts: both render the
 * declaration model built by gen-model.ts, so type names match the Swift
 * output (`OptioTask`, `WsEvent`, …) and code ported from iOS reads the same.
 *
 *   pnpm --filter @optio/shared gen:kotlin
 *   # writes apps/android/core/model/src/main/kotlin/dev/optio/core/model/SharedTypes.kt
 *
 * Mapping (package dev.optio.core.model):
 *   interface / object type alias   → @Serializable data class (`data object` when it has no fields)
 *   string enum / string-literal union → enum class with its wire value in `raw` and an
 *                                     UNKNOWN fallback (companion = RawEnumSerializer)
 *   numeric enum                    → Int-backed enum class (companion = IntEnumSerializer)
 *   discriminated object union      → sealed interface: named structs implement it, inline
 *                                     variants become nested classes, plus `Unknown(raw)`;
 *                                     a generated DiscriminatedUnionSerializer picks the variant
 *   `X | null`, `x?: X`             → nullable with a `null` default
 *   `Date` → java.time.Instant (FlexibleInstantSerializer), `number` → Double
 *   unknown / any / functions / tuples / anything irregular → JsonElement (+ warning)
 *
 * Wire keys stay the property names when they are identifiers (Kotlin keywords
 * are backticked); other keys get a camelCase name and `@SerialName`. Generic
 * types, classes, functions and consts are skipped, like gen-swift. A file
 * whose Kotlin twin is hand-written opts out with a leading
 * `// gen-kotlin: skip-file` comment. (`// gen-swift: skip-file` only affects
 * Swift: glance.ts is hand-written for ActivityKit on iOS but generated here.)
 *
 * OptioJson, FlexibleInstantSerializer, RawEnum and DiscriminatedUnionSerializer
 * are hand-written beside the output.
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import {
  addWarning,
  buildModel,
  defaultInputs,
  pascalCase,
  SHARED_RESERVED_NESTED_NAMES,
  SHARED_RESERVED_TYPE_NAMES,
  type Decl,
  type Entry,
  type IntEnumDecl,
  type ModelOptions,
  type Prop,
  type StringEnumDecl,
  type StructDecl,
  type TypeRef,
  type UnionDecl,
} from "./gen-model.js";

export { defaultInputs };

export interface GenerateKotlinResult {
  kotlin: string;
  warnings: string[];
}

const HEADER = "// GENERATED by packages/shared/scripts/gen-kotlin.ts — do not edit.";

export const KOTLIN_PACKAGE = "dev.optio.core.model";

const ANY = "JsonElement";
const UNKNOWN_RAW = "__unknown__";

/** Hard keywords: backticked when used as property names. */
const KOTLIN_KEYWORDS = new Set([
  "as",
  "break",
  "class",
  "continue",
  "do",
  "else",
  "false",
  "for",
  "fun",
  "if",
  "in",
  "interface",
  "is",
  "null",
  "object",
  "package",
  "return",
  "super",
  "this",
  "throw",
  "true",
  "try",
  "typealias",
  "typeof",
  "val",
  "var",
  "when",
  "while",
]);

/** Kotlin types the generated code spells unqualified. */
const KOTLIN_BUILTIN_NAMES = [
  "Any",
  "Boolean",
  "Double",
  "Int",
  "Long",
  "List",
  "Map",
  "Nothing",
  "String",
  "Unit",
];

/** Imported or hand-written names the generated code refers to. */
const KOTLIN_SUPPORT_NAMES = [
  "Instant",
  "Serializable",
  "SerialName",
  "UseSerializers",
  "Json",
  "JsonElement",
  "JsonObject",
  "OptioJson",
  "RawEnum",
  "RawIntEnum",
  "RawEnumSerializer",
  "IntEnumSerializer",
  "DiscriminatedUnionSerializer",
  "FlexibleInstantSerializer",
];

/** Declared inside every generated union (`Companion` comes from the serialization plugin). */
const UNION_SCOPE_NAMES = ["Unknown", "Serializer", "Companion"];

/** Swift's reserved names (so names match) plus everything Kotlin must not shadow. */
const KOTLIN_RESERVED_TYPE_NAMES: ReadonlySet<string> = new Set([
  ...SHARED_RESERVED_TYPE_NAMES,
  ...KOTLIN_BUILTIN_NAMES,
  ...KOTLIN_SUPPORT_NAMES,
  ...UNION_SCOPE_NAMES,
  "Enum",
  "Suppress",
]);

const KOTLIN_RESERVED_NESTED_NAMES: ReadonlySet<string> = new Set([
  ...SHARED_RESERVED_NESTED_NAMES,
  ...KOTLIN_BUILTIN_NAMES,
  ...KOTLIN_SUPPORT_NAMES,
  "Companion",
]);

/** Variant classes have no Swift twin, so only Kotlin's own conflicts apply. */
const KOTLIN_RESERVED_VARIANT_NAMES: ReadonlySet<string> = new Set([
  ...KOTLIN_BUILTIN_NAMES,
  ...KOTLIN_SUPPORT_NAMES,
  ...UNION_SCOPE_NAMES,
]);

const KOTLIN_MODEL_OPTIONS: ModelOptions = {
  tool: "gen-kotlin",
  skipFilePragma: /^\s*\/\/\s*gen-kotlin:\s*skip-file/m,
  reservedTypeNames: KOTLIN_RESERVED_TYPE_NAMES,
  reservedNestedNames: KOTLIN_RESERVED_NESTED_NAMES,
  anyName: ANY,
  anyDictName: `Map<String, ${ANY}>`,
  union: {
    variantTypeName: (literal) => pascalCase(literal),
    nameBareVariants: true,
    reservedVariantNames: KOTLIN_RESERVED_VARIANT_NAMES,
    scopeNames: UNION_SCOPE_NAMES,
    avoidTopLevelNames: true,
  },
};

// ── Naming helpers ─────────────────────────────────────────────────────────

/** `pr_opened` / `prOpened` / `api-key` / `IfNotPresent` → `PR_OPENED` / … / `IF_NOT_PRESENT`. */
export function upperSnake(s: string): string {
  const parts = s
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .replace(/([A-Z]+)([A-Z][a-z])/g, "$1_$2")
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean);
  if (parts.length === 0) return "EMPTY";
  const out = parts.map((p) => p.toUpperCase()).join("_");
  return /^[0-9]/.test(out) ? `_${out}` : out;
}

export function escapeKotlinIdent(name: string): string {
  return KOTLIN_KEYWORDS.has(name) ? `\`${name}\`` : name;
}

function kotlinString(s: string): string {
  const body = s
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\$/g, "\\$")
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r")
    .replace(/\t/g, "\\t")
    .replace(/[\u0000-\u001f]/g, (c) => `\\u${c.charCodeAt(0).toString(16).padStart(4, "0")}`);
  return `"${body}"`;
}

function indent(text: string, level = 1): string {
  const pad = "    ".repeat(level);
  return text
    .split("\n")
    .map((l) => (l.length ? pad + l : l))
    .join("\n");
}

/**
 * KDoc for `lines`. Comment delimiters inside the text are replaced by HTML
 * entities: Kotlin block comments nest, so a stray opener would swallow the file.
 */
function kdoc(lines: string[]): string {
  if (!lines.length) return "";
  const safe = lines.map((l) => l.replace(/\*\//g, "*&#47;").replace(/\/\*/g, "/&#42;"));
  if (safe.length === 1) return `/** ${safe[0]} */\n`;
  return ["/**", ...safe.map((l) => ` * ${l}`.trimEnd()), " */"].join("\n") + "\n";
}

// ── Generator ──────────────────────────────────────────────────────────────

export function generateKotlin(sourceFiles: string[]): GenerateKotlinResult {
  const model = buildModel(sourceFiles, KOTLIN_MODEL_OPTIONS);
  const warnings = [...model.warnings];
  const warn = (msg: string) => addWarning(warnings, msg);
  const uses = { instant: false, serialName: false, jsonElement: false, serializable: false };
  let usesUnion = false;

  // Named structs that are variants of a union implement its sealed interface.
  const supertypes = new Map<Entry, string[]>();
  const collectSupertypes = (decls: Decl[], scope: string[]) => {
    for (const d of decls) {
      if (d.kind === "struct") collectSupertypes(d.nested, [...scope, d.name]);
      if (d.kind !== "union") continue;
      const inner = [...scope, d.name];
      for (const v of d.variants) {
        if (v.payload.k === "inline") collectSupertypes([v.payload.struct], inner);
        if (v.payload.k !== "entry") continue;
        const list = supertypes.get(v.payload.entry) ?? [];
        const qualified = inner.join(".");
        if (!list.includes(qualified)) list.push(qualified);
        supertypes.set(v.payload.entry, list);
      }
    }
  };
  for (const { decls } of model.entries) collectSupertypes(decls, []);

  // Aliases of nullable types (`type MaybeInner = Inner | null`) are already nullable.
  const aliasOf = new Map<Entry, { type: TypeRef; optional: boolean }>();
  for (const { entry, decls } of model.entries) {
    const own = decls.find((d) => d.kind === "alias" && d.name === entry.typeName);
    if (own?.kind === "alias") aliasOf.set(entry, own);
  }
  const isNullable = (t: TypeRef, seen = new Set<Entry>()): boolean => {
    if (t.k !== "entry" || seen.has(t.entry)) return false;
    const alias = aliasOf.get(t.entry);
    return !!alias && (alias.optional || isNullable(alias.type, seen.add(t.entry)));
  };
  /** `?` for an optional use of `t`, unless `t` is nullable already. */
  const question = (t: TypeRef, optional: boolean) => (optional && !isNullable(t) ? "?" : "");

  function typeText(t: TypeRef): string {
    switch (t.k) {
      case "string":
        return "String";
      case "number":
        return "Double";
      case "boolean":
        return "Boolean";
      case "date":
        uses.instant = true;
        return "Instant";
      case "any":
        uses.jsonElement = true;
        return ANY;
      case "array":
        return `List<${typeText(t.element)}${question(t.element, t.optional)}>`;
      case "map":
        return `Map<String, ${typeText(t.value)}${question(t.value, t.optional)}>`;
      case "entry":
        return t.entry.typeName;
      case "nested":
        return t.name;
    }
  }

  const serialNameOf = (scope: string[], name: string) =>
    [KOTLIN_PACKAGE, ...scope, name].join(".");

  function emitDecl(d: Decl, scope: string[], supers: string[] = []): string {
    switch (d.kind) {
      case "struct":
        return emitStruct(d, scope, supers);
      case "stringEnum":
        return emitStringEnum(d, scope);
      case "intEnum":
        return emitIntEnum(d, scope);
      case "union":
        return emitUnion(d, scope);
      case "alias":
        return `${kdoc(d.docs)}typealias ${d.name} = ${typeText(d.type)}${question(d.type, d.optional)}`;
    }
  }

  function emitProp(p: Prop): string {
    let annotation = "";
    if (p.name !== p.jsonName) {
      uses.serialName = true;
      annotation = `@SerialName(${kotlinString(p.jsonName)}) `;
    }
    const type = `${typeText(p.type)}${p.optional ? `${question(p.type, true)} = null` : ""}`;
    return `${kdoc(p.docs)}${annotation}val ${escapeKotlinIdent(p.name)}: ${type},`;
  }

  function emitStruct(d: StructDecl, scope: string[], supers: string[]): string {
    uses.serializable = true;
    const inherits = supers.length ? ` : ${supers.join(", ")}` : "";
    if (d.props.length === 0)
      return `${kdoc(d.docs)}@Serializable\ndata object ${d.name}${inherits}`;
    const head = `${kdoc(d.docs)}@Serializable\ndata class ${d.name}(\n${indent(d.props.map(emitProp).join("\n"))}\n)${inherits}`;
    if (!d.nested.length) return head;
    const inner = [...scope, d.name];
    return `${head} {\n${indent(d.nested.map((n) => emitDecl(n, inner)).join("\n\n"))}\n}`;
  }

  function emitStringEnum(d: StringEnumDecl, scope: string[]): string {
    uses.serializable = true;
    const used = new Set<string>(["UNKNOWN"]);
    const entries: string[] = [];
    for (const c of d.cases) {
      const base = upperSnake(c.source);
      let name = base;
      if (name === "UNKNOWN") {
        name = "UNKNOWN_VALUE";
        warn(
          `${d.at}: raw value "${c.raw}" collides with the \`UNKNOWN\` fallback; emitted as \`UNKNOWN_VALUE\``,
        );
      }
      let n = 2;
      while (used.has(name)) name = `${base}_${n++}`;
      used.add(name);
      entries.push(`${kdoc(c.docs)}${name}(${kotlinString(c.raw)})`);
    }
    entries.push(
      `/** Fallback for raw values this client does not know about yet. */\nUNKNOWN(${kotlinString(UNKNOWN_RAW)})`,
    );
    const body = [
      `${entries.join(",\n")};`,
      `companion object : RawEnumSerializer<${d.name}>(${kotlinString(serialNameOf(scope, d.name))}, entries, UNKNOWN)`,
    ];
    return `${kdoc(d.docs)}@Serializable(with = ${d.name}.Companion::class)\nenum class ${d.name}(override val raw: String) : RawEnum {\n${indent(body.join("\n\n"))}\n}`;
  }

  function emitIntEnum(d: IntEnumDecl, scope: string[]): string {
    const irregular = d.cases.find(
      (c) => !Number.isInteger(c.value) || Math.abs(c.value) > 2 ** 31 - 1,
    );
    if (irregular) {
      warn(
        `${serialNameOf(scope, d.name)}: value ${irregular.value} does not fit an Int; emitted as typealias Double`,
      );
      return `${kdoc(d.docs)}typealias ${d.name} = Double`;
    }
    uses.serializable = true;
    const used = new Set<string>();
    const entries = d.cases.map((c) => {
      const base = upperSnake(c.source);
      let name = base;
      let n = 2;
      while (used.has(name)) name = `${base}_${n++}`;
      used.add(name);
      return `${kdoc(c.docs)}${name}(${c.value})`;
    });
    const body = [
      `${entries.join(",\n")};`,
      `companion object : IntEnumSerializer<${d.name}>(${kotlinString(serialNameOf(scope, d.name))}, entries)`,
    ];
    return `${kdoc(d.docs)}@Serializable(with = ${d.name}.Companion::class)\nenum class ${d.name}(override val raw: Int) : RawIntEnum {\n${indent(body.join("\n\n"))}\n}`;
  }

  function emitUnion(d: UnionDecl, scope: string[]): string {
    uses.serializable = true;
    usesUnion = true;
    const inner = [...scope, d.name];
    const blocks: string[] = [];
    const decodeLines: string[] = [];
    const encodeLines: string[] = [];
    for (const v of d.variants) {
      const pattern = v.literals.map(kotlinString).join(", ");
      const tag = kotlinString(v.literals[0]);
      const p = v.payload;
      if (p.k === "none") {
        const name = p.name!;
        blocks.push(`data object ${name} : ${d.name}`);
        decodeLines.push(`${pattern} -> ${name}`);
        encodeLines.push(`is ${name} -> tagged(${tag})`);
      } else if (p.k === "inline") {
        const name = p.struct.name;
        blocks.push(emitStruct(p.struct, inner, [d.name]));
        decodeLines.push(
          `${pattern} -> json.decodeFromJsonElement(${name}.serializer(), element.withoutDiscriminator())`,
        );
        encodeLines.push(
          `is ${name} -> tagged(${tag}, json.encodeToJsonElement(${name}.serializer(), value))`,
        );
      } else {
        const name = p.entry.typeName;
        decodeLines.push(`${pattern} -> json.decodeFromJsonElement(${name}.serializer(), element)`);
        encodeLines.push(`is ${name} -> json.encodeToJsonElement(${name}.serializer(), value)`);
      }
    }
    blocks.push(
      `/** Fallback for discriminator values this client does not know about yet. */\ndata class Unknown(val raw: JsonElement) : ${d.name}`,
    );
    blocks.push(
      [
        `object Serializer : DiscriminatedUnionSerializer<${d.name}>(${kotlinString(serialNameOf(scope, d.name))}, ${kotlinString(d.key)}) {`,
        `    override fun decode(tag: String, element: JsonObject, json: Json): ${d.name}? = when (tag) {`,
        ...decodeLines.map((l) => `        ${l}`),
        "        else -> null",
        "    }",
        "",
        `    override fun encode(value: ${d.name}, json: Json): JsonElement = when (value) {`,
        ...encodeLines.map((l) => `        ${l}`),
        "        is Unknown -> value.raw",
        "    }",
        "",
        `    override fun unknown(raw: JsonElement): ${d.name} = Unknown(raw)`,
        "}",
      ].join("\n"),
    );
    return `${kdoc(d.docs)}@Serializable(with = ${d.name}.Serializer::class)\nsealed interface ${d.name} {\n${indent(blocks.join("\n\n"))}\n}`;
  }

  // ── Emit ─────────────────────────────────────────────────────────────────

  const sections: string[] = [];
  let currentFile = "";
  for (const { entry, decls } of model.entries) {
    if (entry.file !== currentFile) {
      if (currentFile) sections.push("// endregion");
      currentFile = entry.file;
      sections.push(`// region ${path.basename(entry.file)}`);
    }
    const own = (d: Decl) => d.kind === "struct" && d.name === entry.typeName;
    sections.push(
      decls.map((d) => emitDecl(d, [], own(d) ? (supertypes.get(entry) ?? []) : [])).join("\n\n"),
    );
  }
  if (currentFile) sections.push("// endregion");

  const imports = [
    uses.instant && "java.time.Instant",
    uses.serialName && "kotlinx.serialization.SerialName",
    uses.serializable && "kotlinx.serialization.Serializable",
    uses.instant && "kotlinx.serialization.UseSerializers",
    usesUnion && "kotlinx.serialization.json.Json",
    (uses.jsonElement || usesUnion) && "kotlinx.serialization.json.JsonElement",
    usesUnion && "kotlinx.serialization.json.JsonObject",
  ].filter((i): i is string => !!i);

  const kotlin = [
    HEADER,
    "//",
    "// Source: packages/shared/src/types/*.ts (+ utils/extract-work-links.ts).",
    "// Regenerate with `pnpm gen:kotlin`; scripts/check-kotlin-types.sh fails when this is stale.",
    "// Hand-written support lives beside this file: OptioJson, FlexibleInstantSerializer,",
    "// RawEnum (enum machinery) and DiscriminatedUnionSerializer (union machinery).",
    "//",
    "// Conventions:",
    "//   • String enums carry an `UNKNOWN` fallback so new server values never fail decoding.",
    "//   • Discriminated unions decode unrecognised variants into `Unknown(raw: JsonElement)`.",
    "//   • TypeScript `Date` fields are `java.time.Instant` (FlexibleInstantSerializer: ISO-8601",
    "//     with or without fractional seconds, or epoch millis / seconds).",
    "//   • TypeScript `number` is `Double`; `unknown` / `any` / irregular shapes are `JsonElement`.",
    "//   • Decode and encode with `OptioJson` (ignoreUnknownKeys, explicitNulls = false).",
    "",
    '@file:Suppress("PropertyName", "KDocUnresolvedReference", "SpellCheckingInspection")',
    ...(uses.instant ? ["@file:UseSerializers(FlexibleInstantSerializer::class)"] : []),
    "",
    `package ${KOTLIN_PACKAGE}`,
    "",
    ...(imports.length ? [...imports.map((i) => `import ${i}`), ""] : []),
    ...sections.flatMap((s) => [s, ""]),
  ].join("\n");

  return { kotlin, warnings };
}

// ── CLI ─────────────────────────────────────────────────────────────────────

export function defaultOutput(): string {
  const here = path.dirname(fileURLToPath(import.meta.url));
  return path.resolve(
    here,
    "../../../apps/android/core/model/src/main/kotlin/dev/optio/core/model/SharedTypes.kt",
  );
}

function main(): void {
  const out = process.argv[2] ? path.resolve(process.argv[2]) : defaultOutput();
  const { kotlin, warnings } = generateKotlin(defaultInputs());
  for (const w of warnings) console.error(`gen-kotlin: warn: ${w}`);
  fs.mkdirSync(path.dirname(out), { recursive: true });
  fs.writeFileSync(out, kotlin);
  console.error(
    `gen-kotlin: wrote ${path.relative(process.cwd(), out)} (${warnings.length} warning(s))`,
  );
}

if (process.argv[1] && pathToFileURL(path.resolve(process.argv[1])).href === import.meta.url) {
  main();
}
