import { afterAll, beforeAll, describe, expect, it } from "vitest";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { camelCase, escapeIdent, generateSwift, pascalCase } from "./gen-swift.js";

let dir: string;

beforeAll(() => {
  dir = fs.mkdtempSync(path.join(os.tmpdir(), "gen-swift-"));
});

afterAll(() => {
  fs.rmSync(dir, { recursive: true, force: true });
});

function fixture(name: string, source: string): string {
  const file = path.join(dir, name);
  fs.writeFileSync(file, source);
  return file;
}

/** Extract one top-level `public struct|enum|typealias NAME …` block. */
function block(swift: string, name: string): string {
  const re = new RegExp(
    `^(?:/// .*\\n)*public (?:struct|enum) ${name}\\b[\\s\\S]*?^\\}$|^public typealias ${name} = .*$`,
    "m",
  );
  const m = swift.match(re);
  if (!m) throw new Error(`no top-level declaration named ${name} in:\n${swift}`);
  return m[0];
}

describe("generateSwift", () => {
  it("emits a header and imports Foundation", () => {
    const f = fixture("header.ts", `export interface A { id: string }`);
    const { swift } = generateSwift([f]);
    expect(
      swift.startsWith("// GENERATED by packages/shared/scripts/gen-swift.ts — do not edit."),
    ).toBe(true);
    expect(swift).toContain("import Foundation");
  });

  it("maps an interface to a Codable struct with a public memberwise init", () => {
    const f = fixture(
      "struct.ts",
      `
      /** A thing. */
      export interface Thing {
        id: string;
        /** How many. */
        count: number;
        ok: boolean;
        when: Date;
        tags: string[];
        meta: Record<string, unknown>;
        blob: unknown;
      }
      `,
    );
    const { swift, warnings } = generateSwift([f]);
    const s = block(swift, "Thing");
    expect(s).toContain("/// A thing.");
    expect(s).toContain("public struct Thing: Codable, Hashable, Sendable {");
    expect(s).toContain("public let id: String");
    expect(s).toContain("/// How many.\n    public let count: Double");
    expect(s).toContain("public let ok: Bool");
    expect(s).toContain("public let when: Date");
    expect(s).toContain("public let tags: [String]");
    expect(s).toContain("public let meta: [String: AnyCodable]");
    expect(s).toContain("public let blob: AnyCodable");
    // Long signatures wrap one parameter per line.
    expect(s).toContain(
      "public init(\n        id: String,\n        count: Double,\n        ok: Bool,\n        when: Date,\n        tags: [String],\n        meta: [String: AnyCodable],\n        blob: AnyCodable\n    ) {",
    );
    expect(s).toContain('case id = "id"');
    expect(warnings).toEqual([]);
  });

  it("makes `?`, `| null` and `| undefined` fields Optional with a nil default", () => {
    const f = fixture(
      "optional.ts",
      `
      export interface Opt {
        a?: string;
        b: string | null;
        c: number | undefined;
        d?: Date | null;
        e: string;
      }
      `,
    );
    const { swift } = generateSwift([f]);
    const s = block(swift, "Opt");
    expect(s).toContain("public let a: String?");
    expect(s).toContain("public let b: String?");
    expect(s).toContain("public let c: Double?");
    expect(s).toContain("public let d: Date?");
    expect(s).toContain("public let e: String\n");
    expect(s).toContain(
      "public init(a: String? = nil, b: String? = nil, c: Double? = nil, d: Date? = nil, e: String) {",
    );
  });

  it("turns a string-literal union into a String enum with an .unknown fallback", () => {
    const f = fixture(
      "union.ts",
      `
      /** Where a terminal came from. */
      export type Source = "manual" | "api-key" | "CHANGES_REQUESTED" | "task:log";
      `,
    );
    const { swift } = generateSwift([f]);
    const e = block(swift, "Source");
    expect(e).toContain("/// Where a terminal came from.");
    expect(e).toContain("public enum Source: String, Codable, Hashable, Sendable, CaseIterable {");
    expect(e).toContain('case manual = "manual"');
    expect(e).toContain('case apiKey = "api-key"');
    expect(e).toContain('case changesRequested = "CHANGES_REQUESTED"');
    expect(e).toContain('case taskLog = "task:log"');
    expect(e).toContain('case unknown = "__unknown__"');
    expect(e).toContain(
      "public static let allCases: [Source] = [.manual, .apiKey, .changesRequested, .taskLog]",
    );
    expect(e).toContain("self = Source(rawValue: raw) ?? .unknown");
  });

  it('renames a real "unknown" literal so the fallback keeps its name', () => {
    const f = fixture("unknown.ts", `export type Status = "healthy" | "unknown";`);
    const { swift, warnings } = generateSwift([f]);
    const e = block(swift, "Status");
    expect(e).toContain('case unknownValue = "unknown"');
    expect(e).toContain('case unknown = "__unknown__"');
    expect(warnings.some((w) => w.includes("Status") && w.includes(".unknownValue"))).toBe(true);
  });

  it("maps TS string enums and numeric enums", () => {
    const f = fixture(
      "enums.ts",
      `
      export enum TaskState {
        PENDING = "pending",
        PR_OPENED = "pr_opened",
      }
      export enum Level { Low, High = 5, Max }
      `,
    );
    const { swift } = generateSwift([f]);
    const s = block(swift, "TaskState");
    expect(s).toContain(
      "public enum TaskState: String, Codable, Hashable, Sendable, CaseIterable {",
    );
    expect(s).toContain('case pending = "pending"');
    expect(s).toContain('case prOpened = "pr_opened"');
    expect(s).toContain('case unknown = "__unknown__"');
    const n = block(swift, "Level");
    expect(n).toContain("public enum Level: Int, Codable, Hashable, Sendable, CaseIterable {");
    expect(n).toContain("case low = 0");
    expect(n).toContain("case high = 5");
    expect(n).toContain("case max = 6");
    expect(n).not.toContain("unknown");
  });

  it("emits inline string-literal unions as nested enums", () => {
    const f = fixture(
      "inline.ts",
      `
      export interface Check {
        status: "queued" | "done";
        conclusion: "success" | "failure" | null;
        type: "task:log";
      }
      `,
    );
    const { swift } = generateSwift([f]);
    const s = block(swift, "Check");
    expect(s).toContain("public enum Status: String, Codable, Hashable, Sendable, CaseIterable {");
    expect(s).toContain("public enum Conclusion: String");
    expect(s).toContain("public let status: Status");
    expect(s).toContain("public let conclusion: Conclusion?");
    // A single literal (a discriminator) stays a plain String.
    expect(s).toContain("public let type: String");
  });

  it("builds a discriminated union enum from inline object variants", () => {
    const f = fixture(
      "disc.ts",
      `
      export type Agent = "claude-code" | "codex";
      /** How to build the process. */
      export type Spec =
        | { kind: "shell" }
        | { kind: "command"; command: string }
        | { kind: "agent"; agent: Agent; prompt?: string };
      `,
    );
    const { swift, warnings } = generateSwift([f]);
    const e = block(swift, "Spec");
    expect(e).toContain("/// How to build the process.");
    expect(e).toContain("public enum Spec: Codable, Hashable, Sendable {");
    expect(e).toContain("case shell\n");
    expect(e).toContain("case command(CommandPayload)");
    expect(e).toContain("case agent(AgentPayload)");
    expect(e).toContain("case unknown(AnyCodable)");
    expect(e).toContain("public struct CommandPayload: Codable, Hashable, Sendable {");
    expect(e).toContain("public let agent: Agent");
    expect(e).toContain("public let prompt: String?");
    expect(e).toContain(
      "private enum DiscriminatorKey: String, CodingKey {\n        case kind\n    }",
    );
    expect(e).toContain('case "shell": self = .shell');
    expect(e).toContain('case "command": self = .command(try CommandPayload(from: decoder))');
    expect(e).toContain("default: self = .unknown(try AnyCodable(from: decoder))");
    expect(e).toContain('try container.encode("command", forKey: .kind)');
    expect(e).toContain("try payload.encode(to: encoder)");
    expect(warnings).toEqual([]);
  });

  it("builds a discriminated union from named interfaces sharing a `type` literal", () => {
    const f = fixture(
      "events.ts",
      `
      export type WsEvent = TaskLogEvent | TaskDoneEvent | PingEvent;
      export interface TaskLogEvent { type: "task:log"; taskId: string; content: string }
      export interface TaskDoneEvent { type: "task:done" | "task:acked"; taskId: string }
      export interface PingEvent { type: "ping" }
      `,
    );
    const { swift, warnings } = generateSwift([f]);
    const e = block(swift, "WsEvent");
    expect(e).toContain("case taskLog(TaskLogEvent)");
    expect(e).toContain("case taskDone(TaskDoneEvent)");
    expect(e).toContain("case ping(PingEvent)");
    expect(e).toContain('case "task:log": self = .taskLog(try TaskLogEvent(from: decoder))');
    expect(e).toContain(
      'case "task:done", "task:acked": self = .taskDone(try TaskDoneEvent(from: decoder))',
    );
    // Named payloads already carry the discriminator, so encode passes straight through.
    expect(e).not.toContain('try container.encode("task:log"');
    expect(e).toContain("case .taskLog(let payload):\n            try payload.encode(to: encoder)");
    expect(block(swift, "TaskLogEvent")).toContain("public let type: String");
    expect(warnings).toEqual([]);
  });

  it("falls back to AnyCodable with a warning for irregular unions", () => {
    const f = fixture(
      "irregular.ts",
      `
      export type Mixed = string | { a: number };
      export type NoKey = { a: string } | { b: string };
      export interface Holder { pair: [string, number]; fn: () => void }
      `,
    );
    const { swift, warnings } = generateSwift([f]);
    expect(block(swift, "Mixed")).toBe("public typealias Mixed = AnyCodable");
    expect(block(swift, "NoKey")).toBe("public typealias NoKey = AnyCodable");
    expect(block(swift, "Holder")).toContain("public let pair: AnyCodable");
    expect(block(swift, "Holder")).toContain("public let fn: AnyCodable");
    expect(warnings.filter((w) => w.includes("emitted as AnyCodable"))).toHaveLength(4);
  });

  it("makes `Named | null` aliases Optional typealiases", () => {
    const f = fixture(
      "nullalias.ts",
      `
      export interface Inner { id: string }
      export type MaybeInner = Inner | null;
      export type Same = Inner;
      `,
    );
    const { swift } = generateSwift([f]);
    expect(block(swift, "MaybeInner")).toBe("public typealias MaybeInner = Inner?");
    expect(block(swift, "Same")).toBe("public typealias Same = Inner");
  });

  it("escapes Swift keywords in field names while preserving the JSON key", () => {
    const f = fixture(
      "keywords.ts",
      `
      export interface Kw {
        default: string;
        in: number;
        protocol?: string;
        "content-type": string;
      }
      `,
    );
    const { swift } = generateSwift([f]);
    const s = block(swift, "Kw");
    expect(s).toContain("public let `default`: String");
    expect(s).toContain("public let `in`: Double");
    expect(s).toContain("public let `protocol`: String?");
    expect(s).toContain("public let contentType: String");
    expect(s).toContain('case `default` = "default"');
    expect(s).toContain('case `in` = "in"');
    expect(s).toContain('case contentType = "content-type"');
    expect(s).toContain("self.`default` = `default`");
    expect(s).toContain(
      "public init(`default`: String, `in`: Double, `protocol`: String? = nil, contentType: String) {",
    );
  });

  it("flattens `extends` and intersections, and nests inline object types", () => {
    const f = fixture(
      "extends.ts",
      `
      export interface Base { id: string; role: string }
      export interface WithUser extends Base { email: string; role: "admin" | "member" }
      export type Both = Base & { extra: boolean };
      export interface Outer {
        user?: { id: string; avatarUrl?: string };
        items: Array<{ path: string }>;
      }
      `,
    );
    const { swift, warnings } = generateSwift([f]);
    const w = block(swift, "WithUser");
    expect(w).toContain("public let id: String");
    expect(w).toContain("public let email: String");
    // Child overrides the inherited field type but keeps its position.
    expect(w).toContain("public let role: Role");
    expect(w.indexOf("public let role")).toBeLessThan(w.indexOf("public let email"));
    const b = block(swift, "Both");
    expect(b).toContain("public struct Both: Codable, Hashable, Sendable {");
    expect(b).toContain("public let extra: Bool");
    const o = block(swift, "Outer");
    expect(o).toContain("public struct User: Codable, Hashable, Sendable {");
    expect(o).toContain("public let user: User?");
    expect(o).toContain("public struct Item: Codable, Hashable, Sendable {");
    expect(o).toContain("public let items: [Item]");
    expect(warnings).toEqual([]);
  });

  it("resolves `keyof typeof CONST` through the type checker", () => {
    const f = fixture(
      "keyof.ts",
      `
      export const PRESETS = { node: { tag: "n" }, base: { tag: "b" } } as const;
      export type PresetId = keyof typeof PRESETS;
      `,
    );
    const { swift, warnings } = generateSwift([f]);
    const e = block(swift, "PresetId");
    expect(e).toContain("public enum PresetId: String");
    expect(e).toContain('case base = "base"');
    expect(e).toContain('case node = "node"');
    expect(warnings).toEqual([]);
  });

  it("skips generics, classes, functions, consts and method-bearing interfaces", () => {
    const f = fixture(
      "skip.ts",
      `
      export interface Box<T> { value: T }
      export class Thing { x = 1 }
      export function go(): void {}
      export const N = 3;
      export interface Api { readonly kind: string; call(): void }
      export interface Holder { api?: Api }
      `,
    );
    const { swift, warnings } = generateSwift([f]);
    expect(swift).not.toContain("Box");
    expect(swift).not.toContain("Thing");
    expect(swift).not.toContain("struct Api");
    expect(block(swift, "Holder")).toContain("public let api: AnyCodable?");
    expect(
      warnings.some((w) => w.endsWith("skip.ts:Api: interface has method members; skipped")),
    ).toBe(true);
  });

  it("maps index-signature interfaces to dictionaries", () => {
    const f = fixture(
      "dict.ts",
      `
      export interface Config { [key: string]: unknown }
      export interface Env { [key: string]: string }
      `,
    );
    const { swift } = generateSwift([f]);
    expect(block(swift, "Config")).toBe("public typealias Config = [String: AnyCodable]");
    expect(block(swift, "Env")).toBe("public typealias Env = [String: String]");
  });

  it("prefixes colliding names across files and orders output by file name", () => {
    const a = fixture("zeta.ts", `export interface Shared { z: string }`);
    const b = fixture(
      "alpha.ts",
      `export interface Shared { a: string }\nexport interface First { x: string }`,
    );
    const { swift, warnings } = generateSwift([a, b]);
    expect(swift.indexOf("// MARK: - alpha.ts")).toBeLessThan(swift.indexOf("// MARK: - zeta.ts"));
    expect(block(swift, "Shared")).toContain("public let a: String");
    expect(block(swift, "ZetaShared")).toContain("public let z: String");
    expect(warnings.some((w) => w.includes("collides") && w.includes("ZetaShared"))).toBe(true);
  });

  it("is deterministic", () => {
    const f = fixture("det.ts", `export interface A { a: string }\nexport type B = "x" | "y";`);
    expect(generateSwift([f]).swift).toBe(generateSwift([f]).swift);
  });
});

describe("naming helpers", () => {
  it("camelCase / pascalCase handle separators and ALL_CAPS words", () => {
    expect(camelCase("api-key")).toBe("apiKey");
    expect(camelCase("CHANGES_REQUESTED")).toBe("changesRequested");
    expect(camelCase("IfNotPresent")).toBe("ifNotPresent");
    expect(camelCase("task:message_delivered")).toBe("taskMessageDelivered");
    expect(camelCase("123abc")).toBe("_123abc");
    expect(pascalCase("setup-files")).toBe("SetupFiles");
  });

  it("escapeIdent backticks Swift keywords only", () => {
    expect(escapeIdent("default")).toBe("`default`");
    expect(escapeIdent("Type")).toBe("`Type`");
    expect(escapeIdent("taskId")).toBe("taskId");
  });
});

describe("reserved Swift type names", () => {
  it("prefixes names that shadow stdlib types", () => {
    const { swift } = generateSwift([
      fixture(
        "reserved.ts",
        `export interface Task { id: string }\nexport interface Ref { task: Task }`,
      ),
    ]);
    expect(swift).toContain("public struct OptioTask");
    expect(swift).toContain("public let task: OptioTask");
    expect(swift).not.toMatch(/public struct Task\b/);
  });
});
