/**
 * gen-swift — emit Swift `Codable` models from the shared TypeScript protocol
 * types so the iOS app (apps/ios) and the server share one wire format.
 *
 *   pnpm --filter @optio/shared gen:swift      # writes apps/ios/Optio/Generated/SharedTypes.swift
 *
 * Mapping (see docs at the top of the generated file for the Swift side):
 *   interface / object type alias   → public struct (Codable, Hashable, Sendable)
 *   string enum / string-literal union → String-raw enum with a `.unknown` fallback
 *   numeric enum                    → Int-raw enum
 *   discriminated object union      → enum with associated payload structs
 *   `X | null`, `x?: X`             → Optional
 *   unknown / any / functions / tuples / anything irregular → AnyCodable (+ warning)
 *
 * Generic types, classes, functions and consts are skipped silently. Interfaces
 * with method members are skipped with a warning (they are not data).
 *
 * The generator is syntactic (AST-driven) so its output is predictable; the
 * type checker is only consulted for `keyof typeof X`-style aliases.
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import ts from "typescript";

export interface GenerateResult {
  swift: string;
  warnings: string[];
}

const HEADER = "// GENERATED by packages/shared/scripts/gen-swift.ts — do not edit.";

/** Files carrying this comment near the top are excluded from generation. */
const SKIP_FILE_PRAGMA = /^\s*\/\/\s*gen-swift:\s*skip-file/m;

const ANY = "AnyCodable";
const UNKNOWN_RAW = "__unknown__";

/** Identifiers that must be backtick-escaped when used as Swift member names. */
/**
 * Type names that shadow Swift stdlib / Foundation types callers use constantly
 * (`Task.sleep`, `Error`, ...). These are emitted with an `Optio` prefix.
 */
const SWIFT_RESERVED_TYPE_NAMES = new Set([
  "Task",
  "Error",
  "Result",
  "Data",
  "Date",
  "URL",
  "Notification",
  "Operation",
  "Timer",
  "Thread",
  "Bundle",
  "Process",
  "Optional",
  "Array",
  "Dictionary",
  "Set",
  "String",
  "Character",
  "Never",
  "Decoder",
  "Encoder",
]);

const SWIFT_KEYWORDS = new Set([
  "default",
  "in",
  "operator",
  "protocol",
  "where",
  "import",
  "class",
  "struct",
  "enum",
  "func",
  "var",
  "let",
  "return",
  "self",
  "Self",
  "Type",
  "internal",
  "public",
  "private",
  "fileprivate",
  "open",
  "static",
  "throws",
  "rethrows",
  "throw",
  "try",
  "catch",
  "is",
  "as",
  "repeat",
  "defer",
  "guard",
  "init",
  "deinit",
  "switch",
  "case",
  "extension",
  "associatedtype",
  "subscript",
  "inout",
  "if",
  "else",
  "for",
  "while",
  "do",
  "break",
  "continue",
  "fallthrough",
  "true",
  "false",
  "nil",
  "super",
  "typealias",
  "Any",
  "Protocol",
  "precedencegroup",
  "actor",
]);

/** Nested type names that would shadow something important inside a struct. */
const RESERVED_TYPE_NAMES = new Set([
  "Type",
  "Protocol",
  "Self",
  "Data",
  "Date",
  "String",
  "Int",
  "Double",
  "Bool",
  "Array",
  "Dictionary",
  "Optional",
  "Error",
  "Result",
  "Set",
  "Decoder",
  "Encoder",
  "CodingKeys",
  "AnyCodable",
]);

const IDENT_RE = /^[A-Za-z_][A-Za-z0-9_]*$/;

// ── Naming helpers ─────────────────────────────────────────────────────────

function words(s: string): string[] {
  return s
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((w) => (w === w.toUpperCase() ? w.toLowerCase() : w));
}

function capitalize(w: string): string {
  return w.charAt(0).toUpperCase() + w.slice(1);
}

export function pascalCase(s: string): string {
  const ws = words(s);
  if (ws.length === 0) return "Empty";
  const out = ws.map(capitalize).join("");
  return /^[0-9]/.test(out) ? `_${out}` : out;
}

export function camelCase(s: string): string {
  const ws = words(s);
  if (ws.length === 0) return "empty";
  const [first, ...rest] = ws;
  const out = first.charAt(0).toLowerCase() + first.slice(1) + rest.map(capitalize).join("");
  return /^[0-9]/.test(out) ? `_${out}` : out;
}

function singular(name: string): string {
  if (/ies$/.test(name)) return name.replace(/ies$/, "y");
  if (/[^s]s$/.test(name)) return name.slice(0, -1);
  return `${name}Item`;
}

export function escapeIdent(name: string): string {
  return SWIFT_KEYWORDS.has(name) ? `\`${name}\`` : name;
}

function swiftString(s: string): string {
  return `"${s
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r")
    .replace(/\t/g, "\\t")}"`;
}

function indent(text: string, level = 1): string {
  const pad = "    ".repeat(level);
  return text
    .split("\n")
    .map((l) => (l.length ? pad + l : l))
    .join("\n");
}

function docLines(lines: string[]): string {
  return lines.length ? lines.map((l) => `/// ${l}`.trimEnd()).join("\n") + "\n" : "";
}

// ── Generator ──────────────────────────────────────────────────────────────

type DeclNode = ts.InterfaceDeclaration | ts.TypeAliasDeclaration | ts.EnumDeclaration;

type EntryKind = "struct" | "dict" | "enum" | "alias" | "skipped";

interface Entry {
  name: string;
  swiftName: string;
  file: string;
  sf: ts.SourceFile;
  node: DeclNode;
  kind: EntryKind;
}

interface Ctx {
  sf: ts.SourceFile;
  /** Swift declarations to nest inside the current container. */
  nested: string[];
  usedNames: Set<string>;
}

interface Mapped {
  swift: string;
  optional: boolean;
}

interface Prop {
  jsonName: string;
  swiftName: string;
  type: string;
  optional: boolean;
  docs: string[];
}

interface Variant {
  literals: string[];
  caseName: string;
  /** Swift type of the associated value, or null for a bare case. */
  payload: string | null;
  /** True when the payload struct already contains the discriminator field. */
  payloadHasDiscriminator: boolean;
}

export function generateSwift(sourceFiles: string[]): GenerateResult {
  const warnings: string[] = [];
  const warn = (msg: string) => {
    if (!warnings.includes(msg)) warnings.push(msg);
  };

  const files = [...new Set(sourceFiles.map((f) => path.resolve(f)))].sort((a, b) => {
    const ba = path.basename(a);
    const bb = path.basename(b);
    return ba < bb ? -1 : ba > bb ? 1 : a < b ? -1 : a > b ? 1 : 0;
  });

  const program = ts.createProgram(files, {
    target: ts.ScriptTarget.ES2022,
    module: ts.ModuleKind.NodeNext,
    moduleResolution: ts.ModuleResolutionKind.NodeNext,
    strict: true,
    noEmit: true,
    skipLibCheck: true,
  });
  const checker = program.getTypeChecker();

  const entries: Entry[] = [];
  const byName = new Map<string, Entry[]>();
  const takenSwiftNames = new Map<string, Entry>();

  const rel = (file: string) => path.relative(process.cwd(), file);
  const where = (e: Entry) => `${rel(e.file)}:${e.name}`;

  // ── Pass 1: register every exported declaration ──────────────────────────

  function isExported(node: ts.Node): boolean {
    return (
      ts.canHaveModifiers(node) &&
      (ts.getModifiers(node) ?? []).some((m) => m.kind === ts.SyntaxKind.ExportKeyword)
    );
  }

  function hasMethods(members: ts.NodeArray<ts.TypeElement>): boolean {
    return members.some(
      (m) =>
        ts.isMethodSignature(m) ||
        ts.isCallSignatureDeclaration(m) ||
        ts.isConstructSignatureDeclaration(m),
    );
  }

  function onlyIndexSignatures(members: ts.NodeArray<ts.TypeElement>): boolean {
    return members.length > 0 && members.every((m) => ts.isIndexSignatureDeclaration(m));
  }

  function classify(node: DeclNode, sf: ts.SourceFile): EntryKind | null {
    if (ts.isEnumDeclaration(node)) return "enum";
    if (node.typeParameters?.length) return null; // generics: skipped silently
    if (ts.isInterfaceDeclaration(node)) {
      if (hasMethods(node.members)) {
        warn(`${rel(sf.fileName)}:${node.name.text}: interface has method members; skipped`);
        return "skipped";
      }
      return onlyIndexSignatures(node.members) ? "dict" : "struct";
    }
    const t = unparen(node.type);
    if (ts.isTypeLiteralNode(t)) {
      if (hasMethods(t.members)) {
        warn(`${rel(sf.fileName)}:${node.name.text}: object type has method members; skipped`);
        return "skipped";
      }
      return onlyIndexSignatures(t.members) ? "dict" : "struct";
    }
    if (ts.isIntersectionTypeNode(t)) return "struct";
    return "alias";
  }

  for (const file of files) {
    const sf = program.getSourceFile(file);
    if (!sf) throw new Error(`gen-swift: could not load ${file}`);
    // A file whose Swift twin is hand-written (e.g. ActivityKit content state
    // in apps/ios/Shared) opts out with a leading `// gen-swift: skip-file`.
    if (SKIP_FILE_PRAGMA.test(sf.getFullText())) continue;
    for (const stmt of sf.statements) {
      if (
        !(
          ts.isInterfaceDeclaration(stmt) ||
          ts.isTypeAliasDeclaration(stmt) ||
          ts.isEnumDeclaration(stmt)
        )
      )
        continue;
      if (!isExported(stmt)) continue;
      const kind = classify(stmt, sf);
      if (kind === null) continue;
      const name = stmt.name.text;
      let swiftName = SWIFT_RESERVED_TYPE_NAMES.has(name) ? `Optio${name}` : name;
      if (takenSwiftNames.has(swiftName)) {
        const prefix = pascalCase(path.basename(file).replace(/\.[^.]+$/, ""));
        swiftName = `${prefix}${name}`;
        let n = 2;
        while (takenSwiftNames.has(swiftName)) swiftName = `${prefix}${name}${n++}`;
        const first = takenSwiftNames.get(name)!;
        warn(
          `${rel(file)}:${name}: name collides with ${rel(first.file)}:${name}; emitted as ${swiftName}`,
        );
      }
      const entry: Entry = { name, swiftName, file, sf, node: stmt, kind };
      entries.push(entry);
      takenSwiftNames.set(swiftName, entry);
      const list = byName.get(name) ?? [];
      list.push(entry);
      byName.set(name, list);
    }
  }

  function resolveRef(name: string, ctx: Ctx): Entry | undefined {
    const list = byName.get(name);
    if (!list) return undefined;
    return list.find((e) => e.sf === ctx.sf) ?? list[0];
  }

  // ── Docs ─────────────────────────────────────────────────────────────────

  function docsOf(node: ts.Node, sf: ts.SourceFile): string[] {
    const lines: string[] = [];
    for (const d of ts.getJSDocCommentsAndTags(node)) {
      if (ts.isJSDoc(d) && d.comment) {
        const text = ts.getTextOfJSDocComment(d.comment) ?? "";
        for (const l of text.split("\n")) lines.push(l.trim());
      }
    }
    for (const r of ts.getTrailingCommentRanges(sf.text, node.end) ?? []) {
      const raw = sf.text.slice(r.pos, r.end);
      if (raw.startsWith("//")) lines.push(raw.slice(2).trim());
    }
    while (lines.length && lines[lines.length - 1] === "") lines.pop();
    return lines;
  }

  // ── Type mapping ─────────────────────────────────────────────────────────

  function unparen(node: ts.TypeNode): ts.TypeNode {
    while (ts.isParenthesizedTypeNode(node)) node = node.type;
    return node;
  }

  function isNullish(node: ts.TypeNode): boolean {
    node = unparen(node);
    if (node.kind === ts.SyntaxKind.UndefinedKeyword || node.kind === ts.SyntaxKind.VoidKeyword)
      return true;
    return ts.isLiteralTypeNode(node) && node.literal.kind === ts.SyntaxKind.NullKeyword;
  }

  function stringLiteralOf(node: ts.TypeNode): string | null {
    node = unparen(node);
    if (ts.isLiteralTypeNode(node)) {
      if (ts.isStringLiteral(node.literal) || ts.isNoSubstitutionTemplateLiteral(node.literal))
        return node.literal.text;
    }
    return null;
  }

  /** All string literals of a literal or literal-union node, else null. */
  function stringLiteralsOf(node: ts.TypeNode): string[] | null {
    node = unparen(node);
    const parts = ts.isUnionTypeNode(node) ? flattenUnion(node) : [node];
    const out: string[] = [];
    for (const p of parts) {
      const s = stringLiteralOf(p);
      if (s === null) return null;
      out.push(s);
    }
    return out;
  }

  function flattenUnion(node: ts.UnionTypeNode): ts.TypeNode[] {
    const out: ts.TypeNode[] = [];
    for (const t of node.types) {
      const u = unparen(t);
      if (ts.isUnionTypeNode(u)) out.push(...flattenUnion(u));
      else out.push(u);
    }
    return out;
  }

  function uniqueNested(ctx: Ctx, base: string): string {
    let name = RESERVED_TYPE_NAMES.has(base) ? `${base}Value` : base;
    let n = 2;
    while (ctx.usedNames.has(name)) name = `${base}${n++}`;
    ctx.usedNames.add(name);
    return name;
  }

  function checkerStringLiterals(node: ts.TypeNode): string[] | null {
    const t = checker.getTypeFromTypeNode(node);
    const parts = t.isUnion() ? t.types : [t];
    if (parts.length === 0) return null;
    const out: string[] = [];
    for (const p of parts) {
      if (!p.isStringLiteral()) return null;
      out.push(p.value);
    }
    return out.sort();
  }

  function mapType(node: ts.TypeNode, ctx: Ctx, hint: string, docs: string[] = []): Mapped {
    node = unparen(node);
    const k = node.kind;
    const any = (reason: string): Mapped => {
      warn(`${rel(ctx.sf.fileName)}: ${hint}: ${reason}; emitted as ${ANY}`);
      return { swift: ANY, optional: false };
    };

    switch (k) {
      case ts.SyntaxKind.StringKeyword:
        return { swift: "String", optional: false };
      case ts.SyntaxKind.NumberKeyword:
        return { swift: "Double", optional: false };
      case ts.SyntaxKind.BooleanKeyword:
        return { swift: "Bool", optional: false };
      case ts.SyntaxKind.AnyKeyword:
      case ts.SyntaxKind.UnknownKeyword:
      case ts.SyntaxKind.ObjectKeyword:
      case ts.SyntaxKind.NeverKeyword:
      case ts.SyntaxKind.SymbolKeyword:
      case ts.SyntaxKind.BigIntKeyword:
        return { swift: ANY, optional: false };
      case ts.SyntaxKind.UndefinedKeyword:
      case ts.SyntaxKind.VoidKeyword:
        return { swift: ANY, optional: true };
      case ts.SyntaxKind.TemplateLiteralType:
        return { swift: "String", optional: false };
      case ts.SyntaxKind.FunctionType:
      case ts.SyntaxKind.ConstructorType:
        return any("function type");
      case ts.SyntaxKind.TupleType:
        return any("tuple type");
      default:
        break;
    }

    if (ts.isLiteralTypeNode(node)) {
      const lit = node.literal;
      if (lit.kind === ts.SyntaxKind.NullKeyword) return { swift: ANY, optional: true };
      if (ts.isStringLiteral(lit) || ts.isNoSubstitutionTemplateLiteral(lit))
        return { swift: "String", optional: false };
      if (ts.isNumericLiteral(lit) || ts.isPrefixUnaryExpression(lit))
        return { swift: "Double", optional: false };
      if (lit.kind === ts.SyntaxKind.TrueKeyword || lit.kind === ts.SyntaxKind.FalseKeyword)
        return { swift: "Bool", optional: false };
      return any("unsupported literal type");
    }

    if (ts.isArrayTypeNode(node)) {
      const el = mapType(node.elementType, ctx, singular(hint));
      return { swift: `[${el.swift}${el.optional ? "?" : ""}]`, optional: false };
    }

    if (ts.isTypeReferenceNode(node)) return mapReference(node, ctx, hint);

    if (ts.isTypeLiteralNode(node)) return mapTypeLiteral(node, ctx, hint, docs);

    if (ts.isUnionTypeNode(node)) return mapUnion(flattenUnion(node), ctx, hint, docs);

    if (ts.isIntersectionTypeNode(node)) {
      const props = intersectionProps(node, ctx);
      if (!props) return any("irregular intersection");
      const name = uniqueNested(ctx, pascalCase(hint));
      ctx.nested.push(emitStruct(name, docs, props, ctx));
      return { swift: name, optional: false };
    }

    if (
      ts.isTypeOperatorNode(node) ||
      ts.isIndexedAccessTypeNode(node) ||
      ts.isTypeQueryNode(node)
    ) {
      const lits = checkerStringLiterals(node);
      if (lits) {
        const name = uniqueNested(ctx, pascalCase(hint));
        ctx.nested.push(
          emitStringEnum(
            name,
            docs,
            lits.map((l) => ({ raw: l, name: camelCase(l), docs: [] })),
            `${rel(ctx.sf.fileName)}: ${hint}`,
          ),
        );
        return { swift: name, optional: false };
      }
      return any(`unresolvable type expression \`${node.getText(ctx.sf)}\``);
    }

    return any(`unsupported type syntax \`${node.getText(ctx.sf)}\``);
  }

  function mapReference(node: ts.TypeReferenceNode, ctx: Ctx, hint: string): Mapped {
    const any = (reason: string): Mapped => {
      warn(`${rel(ctx.sf.fileName)}: ${hint}: ${reason}; emitted as ${ANY}`);
      return { swift: ANY, optional: false };
    };
    if (!ts.isIdentifier(node.typeName)) {
      return any(`qualified type \`${node.typeName.getText(ctx.sf)}\``);
    }
    const name = node.typeName.text;
    const args = node.typeArguments ?? [];

    switch (name) {
      case "Date":
        return { swift: "Date", optional: false };
      case "Array":
      case "ReadonlyArray": {
        if (args.length !== 1) return any("Array without element type");
        const el = mapType(args[0], ctx, singular(hint));
        return { swift: `[${el.swift}${el.optional ? "?" : ""}]`, optional: false };
      }
      case "Record": {
        if (args.length !== 2) return any("Record without type arguments");
        const key = unparen(args[0]);
        if (key.kind !== ts.SyntaxKind.StringKeyword && !stringLiteralsOf(key)) {
          return any("Record with non-string keys");
        }
        const val = mapType(args[1], ctx, singular(hint));
        return { swift: `[String: ${val.swift}${val.optional ? "?" : ""}]`, optional: false };
      }
      case "Readonly":
      case "NonNullable":
        if (args.length === 1) return mapType(args[0], ctx, hint);
        return any(`${name} without type argument`);
      case "Partial":
      case "Required":
      case "Pick":
      case "Omit":
      case "Promise":
      case "Map":
      case "Set":
        return any(`unsupported utility type ${name}`);
      default:
        break;
    }

    if (args.length) return any(`generic reference ${name}<…>`);
    const entry = resolveRef(name, ctx);
    if (!entry) return any(`unresolved type reference ${name}`);
    if (entry.kind === "skipped") return any(`reference to skipped type ${name}`);
    return { swift: entry.swiftName, optional: false };
  }

  function mapTypeLiteral(
    node: ts.TypeLiteralNode,
    ctx: Ctx,
    hint: string,
    docs: string[],
  ): Mapped {
    const index = node.members.find(ts.isIndexSignatureDeclaration);
    if (index) {
      const named = node.members.filter((m) => !ts.isIndexSignatureDeclaration(m));
      if (named.length) {
        warn(
          `${rel(ctx.sf.fileName)}: ${hint}: object with an index signature and ${named.length} named field(s); emitted as [String: ${ANY}] (named fields dropped)`,
        );
        return { swift: `[String: ${ANY}]`, optional: false };
      }
      const val = index.type
        ? mapType(index.type, ctx, singular(hint))
        : { swift: ANY, optional: false };
      return { swift: `[String: ${val.swift}${val.optional ? "?" : ""}]`, optional: false };
    }
    const name = uniqueNested(ctx, pascalCase(hint));
    ctx.nested.push(emitStruct(name, docs, propsOfMembers(node.members, ctx), ctx));
    return { swift: name, optional: false };
  }

  function mapUnion(members: ts.TypeNode[], ctx: Ctx, hint: string, docs: string[]): Mapped {
    const any = (reason: string): Mapped => {
      warn(`${rel(ctx.sf.fileName)}: ${hint}: ${reason}; emitted as ${ANY}`);
      return { swift: ANY, optional: false };
    };
    const optional = members.some(isNullish);
    const rest = members.filter((m) => !isNullish(m));
    if (rest.length === 0) return { swift: ANY, optional: true };

    if (rest.length === 1) {
      const m = mapType(rest[0], ctx, hint, docs);
      return { swift: m.swift, optional: optional || m.optional };
    }

    const literals = rest.map(stringLiteralOf);
    if (literals.every((l) => l !== null)) {
      const name = uniqueNested(ctx, pascalCase(hint));
      ctx.nested.push(
        emitStringEnum(
          name,
          docs,
          (literals as string[]).map((l) => ({ raw: l, name: camelCase(l), docs: [] })),
          `${rel(ctx.sf.fileName)}: ${hint}`,
        ),
      );
      return { swift: name, optional };
    }

    // Primitive widenings: "a" | "b" | string, 1 | 2 | number, true | false.
    const prim = primitiveOf(rest);
    if (prim) return { swift: prim, optional };

    if (rest.every((m) => isObjectish(m, ctx))) {
      const variants = discriminatedVariants(rest, ctx, hint);
      if (variants) {
        const name = uniqueNested(ctx, pascalCase(hint));
        ctx.nested.push(emitUnionEnum(name, docs, variants.key, variants.variants, ctx));
        return { swift: name, optional };
      }
      return any("object union without a common string-literal discriminator (`kind` / `type`)");
    }

    return any("irregular union");
  }

  function primitiveOf(members: ts.TypeNode[]): string | null {
    const kinds = new Set<string>();
    for (const m of members) {
      const u = unparen(m);
      if (u.kind === ts.SyntaxKind.StringKeyword || stringLiteralOf(u) !== null)
        kinds.add("String");
      else if (
        u.kind === ts.SyntaxKind.NumberKeyword ||
        (ts.isLiteralTypeNode(u) &&
          (ts.isNumericLiteral(u.literal) || ts.isPrefixUnaryExpression(u.literal)))
      )
        kinds.add("Double");
      else if (
        u.kind === ts.SyntaxKind.BooleanKeyword ||
        (ts.isLiteralTypeNode(u) &&
          (u.literal.kind === ts.SyntaxKind.TrueKeyword ||
            u.literal.kind === ts.SyntaxKind.FalseKeyword))
      )
        kinds.add("Bool");
      else return null;
    }
    return kinds.size === 1 ? [...kinds][0] : null;
  }

  function isObjectish(node: ts.TypeNode, ctx: Ctx): boolean {
    node = unparen(node);
    if (ts.isTypeLiteralNode(node)) return !node.members.some(ts.isIndexSignatureDeclaration);
    if (ts.isTypeReferenceNode(node) && ts.isIdentifier(node.typeName) && !node.typeArguments) {
      const e = resolveRef(node.typeName.text, ctx);
      return e?.kind === "struct";
    }
    return false;
  }

  // ── Properties ───────────────────────────────────────────────────────────

  function propsOfMembers(members: ts.NodeArray<ts.TypeElement>, ctx: Ctx): ts.PropertySignature[] {
    const out: ts.PropertySignature[] = [];
    for (const m of members) {
      if (ts.isPropertySignature(m)) {
        if (ts.isComputedPropertyName(m.name)) {
          warn(`${rel(ctx.sf.fileName)}: computed property \`${m.name.getText(ctx.sf)}\` skipped`);
          continue;
        }
        out.push(m);
      } else if (ts.isMethodSignature(m)) {
        warn(`${rel(ctx.sf.fileName)}: method \`${m.name.getText(ctx.sf)}\` skipped`);
      }
    }
    return out;
  }

  function propName(p: ts.PropertySignature): string {
    const n = p.name;
    if (ts.isIdentifier(n) || ts.isPrivateIdentifier(n)) return n.text;
    if (ts.isStringLiteral(n) || ts.isNumericLiteral(n) || ts.isNoSubstitutionTemplateLiteral(n))
      return n.text;
    return n.getText();
  }

  function mergeProps(lists: ts.PropertySignature[][]): ts.PropertySignature[] {
    const order: string[] = [];
    const map = new Map<string, ts.PropertySignature>();
    for (const list of lists) {
      for (const p of list) {
        const n = propName(p);
        if (!map.has(n)) order.push(n);
        map.set(n, p); // later declarations override inherited ones
      }
    }
    return order.map((n) => map.get(n)!);
  }

  const propsCache = new Map<Entry, ts.PropertySignature[] | null>();

  /** Flattened property list of a struct-kind entry (extends / intersections resolved). */
  function propsOfEntry(entry: Entry, seen: Set<Entry> = new Set()): ts.PropertySignature[] | null {
    if (propsCache.has(entry)) return propsCache.get(entry)!;
    if (seen.has(entry)) {
      warn(`${where(entry)}: circular extends chain`);
      return null;
    }
    seen.add(entry);
    const ctx = newCtx(entry.sf);
    let result: ts.PropertySignature[] | null = null;
    const node = entry.node;
    if (ts.isInterfaceDeclaration(node)) {
      const lists: ts.PropertySignature[][] = [];
      for (const h of node.heritageClauses ?? []) {
        if (h.token !== ts.SyntaxKind.ExtendsKeyword) continue;
        for (const t of h.types) {
          const parentName = t.expression.getText(entry.sf);
          const parent = ts.isIdentifier(t.expression) ? resolveRef(parentName, ctx) : undefined;
          if (t.typeArguments?.length || !parent || parent.kind !== "struct") {
            warn(
              `${where(entry)}: cannot flatten \`extends ${t.getText(entry.sf)}\`; its fields are omitted`,
            );
            continue;
          }
          const parentProps = propsOfEntry(parent, seen);
          if (parentProps) lists.push(parentProps);
        }
      }
      lists.push(propsOfMembers(node.members, ctx));
      result = mergeProps(lists);
    } else if (ts.isTypeAliasDeclaration(node)) {
      const t = unparen(node.type);
      if (ts.isTypeLiteralNode(t)) result = propsOfMembers(t.members, ctx);
      else if (ts.isIntersectionTypeNode(t)) result = intersectionProps(t, ctx, seen);
    }
    propsCache.set(entry, result);
    return result;
  }

  function intersectionProps(
    node: ts.IntersectionTypeNode,
    ctx: Ctx,
    seen: Set<Entry> = new Set(),
  ): ts.PropertySignature[] | null {
    const lists: ts.PropertySignature[][] = [];
    for (const part of node.types) {
      const p = unparen(part);
      if (ts.isTypeLiteralNode(p) && !p.members.some(ts.isIndexSignatureDeclaration)) {
        lists.push(propsOfMembers(p.members, ctx));
        continue;
      }
      if (ts.isTypeReferenceNode(p) && ts.isIdentifier(p.typeName) && !p.typeArguments) {
        const e = resolveRef(p.typeName.text, ctx);
        if (e?.kind === "struct") {
          const props = propsOfEntry(e, seen);
          if (props) {
            lists.push(props);
            continue;
          }
        }
      }
      return null;
    }
    return mergeProps(lists);
  }

  function buildProps(sigs: ts.PropertySignature[], ctx: Ctx): Prop[] {
    const used = new Set<string>();
    const out: Prop[] = [];
    for (const sig of sigs) {
      const jsonName = propName(sig);
      let swiftName = IDENT_RE.test(jsonName) ? jsonName : camelCase(jsonName);
      let n = 2;
      while (used.has(swiftName)) swiftName = `${swiftName}${n++}`;
      used.add(swiftName);
      const docs = docsOf(sig, ctx.sf);
      const mapped = sig.type
        ? mapType(sig.type, ctx, jsonName, [])
        : { swift: ANY, optional: false };
      out.push({
        jsonName,
        swiftName,
        type: mapped.swift,
        optional: mapped.optional || !!sig.questionToken,
        docs,
      });
    }
    return out;
  }

  // ── Discriminated unions ─────────────────────────────────────────────────

  interface MemberShape {
    props: ts.PropertySignature[];
    /** Set when the member is a reference to a named struct. */
    ref?: Entry;
    ctx: Ctx;
  }

  function memberShape(node: ts.TypeNode, ctx: Ctx): MemberShape | null {
    node = unparen(node);
    if (ts.isTypeLiteralNode(node)) return { props: propsOfMembers(node.members, ctx), ctx };
    if (ts.isTypeReferenceNode(node) && ts.isIdentifier(node.typeName)) {
      const e = resolveRef(node.typeName.text, ctx);
      if (!e || e.kind !== "struct") return null;
      const props = propsOfEntry(e);
      if (!props) return null;
      return { props, ref: e, ctx: newCtx(e.sf) };
    }
    return null;
  }

  function discriminatedVariants(
    members: ts.TypeNode[],
    ctx: Ctx,
    hint: string,
  ): { key: string; variants: Variant[] } | null {
    const shapes: MemberShape[] = [];
    for (const m of members) {
      const s = memberShape(m, ctx);
      if (!s) return null;
      shapes.push(s);
    }
    // Candidate keys: present in every member with a string-literal type.
    const literalKeys = (s: MemberShape) => {
      const keys = new Map<string, string[]>();
      for (const p of s.props) {
        if (!p.type || p.questionToken) continue;
        const lits = stringLiteralsOf(p.type);
        if (lits) keys.set(propName(p), lits);
      }
      return keys;
    };
    const perMember = shapes.map(literalKeys);
    const common = [...perMember[0].keys()].filter((k) => perMember.every((m) => m.has(k)));
    if (common.length === 0) return null;
    const key =
      common.find((k) => k === "kind") ?? common.find((k) => k === "type") ?? [...common].sort()[0];

    const variants: Variant[] = [];
    const seenLits = new Set<string>();
    const seenCases = new Set<string>();
    for (let i = 0; i < shapes.length; i++) {
      const s = shapes[i];
      const literals = perMember[i].get(key)!;
      for (const l of literals) {
        if (seenLits.has(l)) {
          warn(
            `${rel(ctx.sf.fileName)}: ${hint}: discriminator value "${l}" appears in more than one member`,
          );
          return null;
        }
        seenLits.add(l);
      }
      let caseName = camelCase(literals[0]);
      if (caseName === "unknown") caseName = "unknownValue";
      let n = 2;
      while (seenCases.has(caseName)) caseName = `${camelCase(literals[0])}${n++}`;
      seenCases.add(caseName);
      if (s.ref) {
        variants.push({
          literals,
          caseName,
          payload: s.ref.swiftName,
          payloadHasDiscriminator: true,
        });
      } else {
        const rest = s.props.filter((p) => propName(p) !== key);
        if (rest.length === 0) {
          variants.push({ literals, caseName, payload: null, payloadHasDiscriminator: false });
        } else {
          variants.push({
            literals,
            caseName,
            payload: `${pascalCase(literals[0])}Payload`,
            payloadHasDiscriminator: false,
          });
          // The payload struct is emitted by emitUnionEnum; stash the props on the variant.
          (variants[variants.length - 1] as Variant & { props?: ts.PropertySignature[] }).props =
            rest;
        }
      }
    }
    return { key, variants };
  }

  // ── Emitters ─────────────────────────────────────────────────────────────

  function newCtx(sf: ts.SourceFile): Ctx {
    return { sf, nested: [], usedNames: new Set() };
  }

  function emitStruct(
    name: string,
    docs: string[],
    sigs: ts.PropertySignature[],
    parent: Ctx,
  ): string {
    const ctx = newCtx(parent.sf);
    ctx.usedNames.add(name);
    const props = buildProps(sigs, ctx);
    const parts: string[] = [];
    if (ctx.nested.length) parts.push(ctx.nested.join("\n\n"));

    if (props.length) {
      parts.push(
        props
          .map(
            (p) =>
              `${docLines(p.docs)}public let ${escapeIdent(p.swiftName)}: ${p.type}${p.optional ? "?" : ""}`,
          )
          .join("\n"),
      );
      parts.push(
        [
          "private enum CodingKeys: String, CodingKey {",
          ...props.map((p) => `    case ${escapeIdent(p.swiftName)} = ${swiftString(p.jsonName)}`),
          "}",
        ].join("\n"),
      );
      const params = props
        .map((p) => `${escapeIdent(p.swiftName)}: ${p.type}${p.optional ? "? = nil" : ""}`)
        .join(", ");
      const header = `public init(${params}) {`;
      parts.push(
        [
          header.length > 96
            ? `public init(\n${indent(params.split(", ").join(",\n"))}\n) {`
            : header,
          ...props.map((p) => `    self.${escapeIdent(p.swiftName)} = ${escapeIdent(p.swiftName)}`),
          "}",
        ].join("\n"),
      );
    } else {
      parts.push("public init() {}");
    }

    return `${docLines(docs)}public struct ${name}: Codable, Hashable, Sendable {\n${indent(parts.join("\n\n"))}\n}`;
  }

  interface EnumCase {
    raw: string;
    name: string;
    docs: string[];
  }

  function emitStringEnum(name: string, docs: string[], cases: EnumCase[], at = name): string {
    const used = new Set<string>(["unknown"]);
    const lines: string[] = [];
    const known: string[] = [];
    for (const c of cases) {
      let caseName = c.name;
      if (caseName === "unknown") {
        caseName = "unknownValue";
        warn(
          `${at}: raw value "${c.raw}" collides with the \`.unknown\` fallback; emitted as \`.unknownValue\``,
        );
      }
      let n = 2;
      while (used.has(caseName)) caseName = `${c.name}${n++}`;
      used.add(caseName);
      known.push(caseName);
      lines.push(`${docLines(c.docs)}case ${escapeIdent(caseName)} = ${swiftString(c.raw)}`);
    }
    lines.push(
      `/// Fallback for raw values this client does not know about yet.\ncase unknown = ${swiftString(UNKNOWN_RAW)}`,
    );
    const body = [
      lines.join("\n"),
      `public static let allCases: [${name}] = [${known.map((k) => `.${k}`).join(", ")}]`,
      [
        "public init(from decoder: any Decoder) throws {",
        "    let raw = try decoder.singleValueContainer().decode(String.self)",
        `    self = ${name}(rawValue: raw) ?? .unknown`,
        "}",
      ].join("\n"),
    ];
    return `${docLines(docs)}public enum ${name}: String, Codable, Hashable, Sendable, CaseIterable {\n${indent(body.join("\n\n"))}\n}`;
  }

  function emitIntEnum(
    name: string,
    docs: string[],
    cases: { value: number; name: string; docs: string[] }[],
  ): string {
    const used = new Set<string>();
    const lines: string[] = [];
    for (const c of cases) {
      let caseName = c.name;
      let n = 2;
      while (used.has(caseName)) caseName = `${c.name}${n++}`;
      used.add(caseName);
      lines.push(`${docLines(c.docs)}case ${escapeIdent(caseName)} = ${c.value}`);
    }
    return `${docLines(docs)}public enum ${name}: Int, Codable, Hashable, Sendable, CaseIterable {\n${indent(lines.join("\n"))}\n}`;
  }

  function emitUnionEnum(
    name: string,
    docs: string[],
    key: string,
    variants: Variant[],
    parent: Ctx,
  ): string {
    const ctx = newCtx(parent.sf);
    ctx.usedNames.add(name);
    const cases: string[] = [];
    const payloadStructs: string[] = [];
    for (const v of variants) {
      const props = (v as Variant & { props?: ts.PropertySignature[] }).props;
      if (props && v.payload) {
        const structName = uniqueNested(ctx, v.payload);
        v.payload = structName;
        payloadStructs.push(emitStruct(structName, [], props, ctx));
      }
      cases.push(
        v.payload
          ? `case ${escapeIdent(v.caseName)}(${v.payload})`
          : `case ${escapeIdent(v.caseName)}`,
      );
    }
    cases.push(
      `/// Fallback for discriminator values this client does not know about yet.\ncase unknown(${ANY})`,
    );

    const decodeLines = [
      "public init(from decoder: any Decoder) throws {",
      "    let container = try decoder.container(keyedBy: DiscriminatorKey.self)",
      `    let discriminator = try container.decodeIfPresent(String.self, forKey: .${escapeIdent(key)}) ?? ""`,
      "    switch discriminator {",
    ];
    for (const v of variants) {
      const pattern = v.literals.map(swiftString).join(", ");
      decodeLines.push(
        v.payload
          ? `    case ${pattern}: self = .${v.caseName}(try ${v.payload}(from: decoder))`
          : `    case ${pattern}: self = .${v.caseName}`,
      );
    }
    decodeLines.push(`    default: self = .unknown(try ${ANY}(from: decoder))`, "    }", "}");

    const encodeLines = [
      "public func encode(to encoder: any Encoder) throws {",
      "    switch self {",
    ];
    for (const v of variants) {
      if (v.payload && v.payloadHasDiscriminator) {
        encodeLines.push(
          `    case .${v.caseName}(let payload):`,
          "        try payload.encode(to: encoder)",
        );
      } else if (v.payload) {
        encodeLines.push(
          `    case .${v.caseName}(let payload):`,
          "        var container = encoder.container(keyedBy: DiscriminatorKey.self)",
          `        try container.encode(${swiftString(v.literals[0])}, forKey: .${escapeIdent(key)})`,
          "        try payload.encode(to: encoder)",
        );
      } else {
        encodeLines.push(
          `    case .${v.caseName}:`,
          "        var container = encoder.container(keyedBy: DiscriminatorKey.self)",
          `        try container.encode(${swiftString(v.literals[0])}, forKey: .${escapeIdent(key)})`,
        );
      }
    }
    encodeLines.push(
      "    case .unknown(let value):",
      "        try value.encode(to: encoder)",
      "    }",
      "}",
    );

    const rawKey = IDENT_RE.test(key)
      ? `case ${escapeIdent(key)}`
      : `case ${escapeIdent(camelCase(key))} = ${swiftString(key)}`;
    const body = [
      cases.join("\n"),
      ...payloadStructs,
      `private enum DiscriminatorKey: String, CodingKey {\n    ${rawKey}\n}`,
      decodeLines.join("\n"),
      encodeLines.join("\n"),
    ];
    return `${docLines(docs)}public enum ${name}: Codable, Hashable, Sendable {\n${indent(body.join("\n\n"))}\n}`;
  }

  function emitTsEnum(entry: Entry): string {
    const node = entry.node as ts.EnumDeclaration;
    const docs = docsOf(node, entry.sf);
    const members = node.members;
    const memberName = (m: ts.EnumMember) =>
      ts.isIdentifier(m.name) || ts.isStringLiteral(m.name)
        ? m.name.text
        : m.name.getText(entry.sf);
    const allString = members.every((m) => m.initializer && ts.isStringLiteral(m.initializer));
    if (allString) {
      return emitStringEnum(
        entry.swiftName,
        docs,
        members.map((m) => ({
          raw: (m.initializer as ts.StringLiteral).text,
          name: camelCase(memberName(m)),
          docs: docsOf(m, entry.sf),
        })),
        where(entry),
      );
    }
    const cases: { value: number; name: string; docs: string[] }[] = [];
    let next = 0;
    for (const m of members) {
      let value = next;
      if (m.initializer) {
        const init = m.initializer;
        if (ts.isNumericLiteral(init)) value = Number(init.text);
        else if (
          ts.isPrefixUnaryExpression(init) &&
          init.operator === ts.SyntaxKind.MinusToken &&
          ts.isNumericLiteral(init.operand)
        )
          value = -Number(init.operand.text);
        else {
          warn(`${where(entry)}: enum has a non-literal initializer; emitted as typealias ${ANY}`);
          return `${docLines(docs)}public typealias ${entry.swiftName} = ${ANY}`;
        }
      }
      next = value + 1;
      cases.push({ value, name: camelCase(memberName(m)), docs: docsOf(m, entry.sf) });
    }
    return emitIntEnum(entry.swiftName, docs, cases);
  }

  function emitEntry(entry: Entry): string | null {
    const docs = docsOf(entry.node, entry.sf);
    const ctx = newCtx(entry.sf);
    switch (entry.kind) {
      case "skipped":
        return null;
      case "enum":
        return emitTsEnum(entry);
      case "dict": {
        const node = entry.node;
        const members = ts.isInterfaceDeclaration(node)
          ? node.members
          : (unparen((node as ts.TypeAliasDeclaration).type) as ts.TypeLiteralNode).members;
        const index = members.find(ts.isIndexSignatureDeclaration)!;
        const val = index.type
          ? mapType(index.type, ctx, entry.swiftName)
          : { swift: ANY, optional: false };
        const hoisted = ctx.nested.length ? ctx.nested.join("\n\n") + "\n\n" : "";
        return `${hoisted}${docLines(docs)}public typealias ${entry.swiftName} = [String: ${val.swift}${val.optional ? "?" : ""}]`;
      }
      case "struct": {
        const props = propsOfEntry(entry);
        if (!props) {
          warn(`${where(entry)}: irregular intersection; emitted as typealias ${ANY}`);
          return `${docLines(docs)}public typealias ${entry.swiftName} = ${ANY}`;
        }
        return emitStruct(entry.swiftName, docs, props, ctx);
      }
      case "alias": {
        const node = entry.node as ts.TypeAliasDeclaration;
        const single = stringLiteralOf(node.type);
        if (single !== null) {
          // A one-member "union" — still an enum so the server can grow it.
          return emitStringEnum(
            entry.swiftName,
            docs,
            [{ raw: single, name: camelCase(single), docs: [] }],
            where(entry),
          );
        }
        const mapped = mapType(node.type, ctx, entry.swiftName, docs);
        // A union / keyof alias emits a top-level enum named after the alias.
        const own = ctx.nested.filter(
          (d) => d.includes(`enum ${entry.swiftName}:`) || d.includes(`struct ${entry.swiftName}:`),
        );
        const others = ctx.nested.filter((d) => !own.includes(d));
        const hoisted = others.length ? others.join("\n\n") + "\n\n" : "";
        if (own.length && mapped.swift === entry.swiftName) {
          if (mapped.optional) {
            warn(
              `${where(entry)}: \`null\` in a top-level union is dropped; declare fields using it as optional`,
            );
          }
          return hoisted + own.join("\n\n");
        }
        return `${hoisted}${docLines(docs)}public typealias ${entry.swiftName} = ${mapped.swift}${mapped.optional ? "?" : ""}`;
      }
    }
  }

  // ── Pass 2: emit ─────────────────────────────────────────────────────────

  const sections: string[] = [];
  let currentFile = "";
  for (const entry of entries) {
    const decl = emitEntry(entry);
    if (decl === null) continue;
    if (entry.file !== currentFile) {
      currentFile = entry.file;
      sections.push(`// MARK: - ${path.basename(entry.file)}`);
    }
    sections.push(decl);
  }

  const swift = [
    HEADER,
    "//",
    "// Source: packages/shared/src/types/*.ts (+ utils/extract-work-links.ts).",
    "// Regenerate with `pnpm gen:swift`. AnyCodable lives in AnyCodable.swift (hand-written).",
    "//",
    "// Conventions:",
    "//   • String enums carry a `.unknown` fallback so new server values never fail decoding.",
    "//   • Discriminated unions decode unrecognised variants into `.unknown(AnyCodable)`.",
    "//   • TypeScript `Date` fields are `Date`; configure your JSONDecoder's dateDecodingStrategy.",
    "//   • TypeScript `number` is `Double`.",
    "",
    "import Foundation",
    "",
    ...sections.flatMap((s) => [s, ""]),
  ].join("\n");

  return { swift, warnings };
}

// ── CLI ─────────────────────────────────────────────────────────────────────

export function defaultInputs(): string[] {
  const here = path.dirname(fileURLToPath(import.meta.url));
  const typesDir = path.resolve(here, "../src/types");
  const files = fs
    .readdirSync(typesDir)
    .filter((f) => f.endsWith(".ts") && !f.endsWith(".test.ts") && !f.endsWith(".d.ts"))
    .map((f) => path.join(typesDir, f));
  files.push(path.resolve(here, "../src/utils/extract-work-links.ts"));
  return files;
}

export function defaultOutput(): string {
  const here = path.dirname(fileURLToPath(import.meta.url));
  return path.resolve(here, "../../../apps/ios/Optio/Generated/SharedTypes.swift");
}

function main(): void {
  const out = process.argv[2] ? path.resolve(process.argv[2]) : defaultOutput();
  const { swift, warnings } = generateSwift(defaultInputs());
  for (const w of warnings) console.error(`gen-swift: warn: ${w}`);
  fs.mkdirSync(path.dirname(out), { recursive: true });
  fs.writeFileSync(out, swift);
  console.error(
    `gen-swift: wrote ${path.relative(process.cwd(), out)} (${warnings.length} warning(s))`,
  );
}

if (process.argv[1] && pathToFileURL(path.resolve(process.argv[1])).href === import.meta.url) {
  main();
}
