import { afterAll, beforeAll, describe, expect, it } from "vitest";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { defaultInputs, escapeKotlinIdent, generateKotlin, upperSnake } from "./gen-kotlin.js";
import { generateSwift } from "./gen-swift.js";

let dir: string;

beforeAll(() => {
  dir = fs.mkdtempSync(path.join(os.tmpdir(), "gen-kotlin-"));
});

afterAll(() => {
  fs.rmSync(dir, { recursive: true, force: true });
});

function fixture(name: string, source: string): string {
  const file = path.join(dir, name);
  fs.writeFileSync(file, source);
  return file;
}

const DECL_START = /^(?:data class|data object|enum class|sealed interface|typealias) (\w+)/;

/** Extract one top-level declaration (with its KDoc and annotations) by name. */
function block(kotlin: string, name: string): string {
  const lines = kotlin.split("\n");
  const start = lines.findIndex((l) => DECL_START.exec(l)?.[1] === name);
  if (start < 0) throw new Error(`no top-level declaration named ${name} in:\n${kotlin}`);
  let first = start;
  while (first > 0 && /^(?:@|\/\*\*| \*)/.test(lines[first - 1])) first--;
  const head = lines[start];
  if (/^(?:typealias|data object)/.test(head)) return lines.slice(first, start + 1).join("\n");
  let end = start;
  if (!head.endsWith("{")) {
    // A data class: its parameter list closes at column 0, maybe opening a body.
    end = start + 1;
    while (end < lines.length && !/^\)/.test(lines[end])) end++;
    if (!lines[end].endsWith("{")) return lines.slice(first, end + 1).join("\n");
  }
  end++;
  while (end < lines.length && lines[end] !== "}") end++;
  return lines.slice(first, end + 1).join("\n");
}

/** Top-level type names declared by generated Kotlin / Swift. */
function kotlinNames(kotlin: string): string[] {
  return kotlin
    .split("\n")
    .map((l) => DECL_START.exec(l)?.[1])
    .filter((n): n is string => !!n);
}

function swiftNames(swift: string): string[] {
  return [...swift.matchAll(/^public (?:struct|enum|typealias) (\w+)/gm)].map((m) => m[1]);
}

// Every case builds a fresh TypeScript program; CI runners with coverage on
// can take a few seconds per program, so give these room beyond the 5s default.
const PROGRAM_TIMEOUT_MS = 60_000;

describe("generateKotlin", { timeout: PROGRAM_TIMEOUT_MS }, () => {
  it("emits a header, the package and only the imports it uses", () => {
    const f = fixture("header.ts", `export interface A { id: string }`);
    const { kotlin } = generateKotlin([f]);
    expect(
      kotlin.startsWith("// GENERATED by packages/shared/scripts/gen-kotlin.ts — do not edit."),
    ).toBe(true);
    expect(kotlin).toContain("\npackage dev.optio.core.model\n");
    expect(kotlin).toContain("import kotlinx.serialization.Serializable");
    expect(kotlin).not.toContain("import java.time.Instant");
    expect(kotlin).not.toContain("@file:UseSerializers");
    expect(kotlin).not.toContain("import kotlinx.serialization.json.JsonElement");
    expect(kotlin).toContain("// region header.ts");
    expect(kotlin.trimEnd().endsWith("// endregion")).toBe(true);
  });

  it("maps an interface to a @Serializable data class", () => {
    const f = fixture(
      "struct.ts",
      `
      /** A thing. */
      export interface Thing {
        id: string;
        /** How many. */
        count: number;
        ok: boolean;
        when: Date;
        tags: string[];
        meta: Record<string, unknown>;
        blob: unknown;
      }
      `,
    );
    const { kotlin, warnings } = generateKotlin([f]);
    const s = block(kotlin, "Thing");
    expect(s).toBe(
      [
        "/** A thing. */",
        "@Serializable",
        "data class Thing(",
        "    val id: String,",
        "    /** How many. */",
        "    val count: Double,",
        "    val ok: Boolean,",
        "    val `when`: Instant,",
        "    val tags: List<String>,",
        "    val meta: Map<String, JsonElement>,",
        "    val blob: JsonElement,",
        ")",
      ].join("\n"),
    );
    expect(kotlin).toContain("@file:UseSerializers(FlexibleInstantSerializer::class)");
    expect(kotlin).toContain("import java.time.Instant");
    expect(kotlin).toContain("import kotlinx.serialization.json.JsonElement");
    expect(warnings).toEqual([]);
  });

  it("makes `?`, `| null` and `| undefined` fields nullable with a null default", () => {
    const f = fixture(
      "optional.ts",
      `
      export interface Opt {
        a?: string;
        b: string | null;
        c: number | undefined;
        d?: Date | null;
        e: string;
      }
      `,
    );
    const s = block(generateKotlin([f]).kotlin, "Opt");
    expect(s).toContain("    val a: String? = null,");
    expect(s).toContain("    val b: String? = null,");
    expect(s).toContain("    val c: Double? = null,");
    expect(s).toContain("    val d: Instant? = null,");
    expect(s).toContain("    val e: String,");
  });

  it("turns a string-literal union into an enum class with an UNKNOWN fallback", () => {
    const f = fixture(
      "union.ts",
      `
      /** Where a terminal came from. */
      export type Source = "manual" | "api-key" | "CHANGES_REQUESTED" | "task:log";
      `,
    );
    const e = block(generateKotlin([f]).kotlin, "Source");
    expect(e).toBe(
      [
        "/** Where a terminal came from. */",
        "@Serializable(with = Source.Companion::class)",
        "enum class Source(override val raw: String) : RawEnum {",
        '    MANUAL("manual"),',
        '    API_KEY("api-key"),',
        '    CHANGES_REQUESTED("CHANGES_REQUESTED"),',
        '    TASK_LOG("task:log"),',
        "    /** Fallback for raw values this client does not know about yet. */",
        '    UNKNOWN("__unknown__");',
        "",
        '    companion object : RawEnumSerializer<Source>("dev.optio.core.model.Source", entries, UNKNOWN)',
        "}",
      ].join("\n"),
    );
  });

  it('renames a real "unknown" literal so the fallback keeps its name', () => {
    const f = fixture("unknown.ts", `export type Status = "healthy" | "unknown";`);
    const { kotlin, warnings } = generateKotlin([f]);
    const e = block(kotlin, "Status");
    expect(e).toContain('UNKNOWN_VALUE("unknown"),');
    expect(e).toContain('UNKNOWN("__unknown__");');
    expect(warnings.some((w) => w.includes("Status") && w.includes("UNKNOWN_VALUE"))).toBe(true);
  });

  it("maps TS string enums and numeric enums", () => {
    const f = fixture(
      "enums.ts",
      `
      export enum TaskState {
        PENDING = "pending",
        PR_OPENED = "pr_opened",
      }
      export enum Level { Low, High = 5, Max }
      `,
    );
    const { kotlin } = generateKotlin([f]);
    const s = block(kotlin, "TaskState");
    expect(s).toContain("enum class TaskState(override val raw: String) : RawEnum {");
    expect(s).toContain('PENDING("pending"),');
    expect(s).toContain('PR_OPENED("pr_opened"),');
    expect(s).toContain('UNKNOWN("__unknown__");');
    const n = block(kotlin, "Level");
    expect(n).toContain("@Serializable(with = Level.Companion::class)");
    expect(n).toContain("enum class Level(override val raw: Int) : RawIntEnum {");
    expect(n).toContain("    LOW(0),\n    HIGH(5),\n    MAX(6);");
    expect(n).toContain(
      'companion object : IntEnumSerializer<Level>("dev.optio.core.model.Level", entries)',
    );
    expect(n).not.toContain("UNKNOWN");
  });

  it("emits inline string-literal unions as nested enums", () => {
    const f = fixture(
      "inline.ts",
      `
      export interface Check {
        status: "queued" | "done";
        conclusion: "success" | "failure" | null;
        type: "task:log";
      }
      `,
    );
    const s = block(generateKotlin([f]).kotlin, "Check");
    expect(s).toContain("    @Serializable(with = Status.Companion::class)");
    expect(s).toContain("    enum class Status(override val raw: String) : RawEnum {");
    expect(s).toContain(
      '        companion object : RawEnumSerializer<Status>("dev.optio.core.model.Check.Status", entries, UNKNOWN)',
    );
    expect(s).toContain("    enum class Conclusion(override val raw: String) : RawEnum {");
    expect(s).toContain("    val status: Status,");
    expect(s).toContain("    val conclusion: Conclusion? = null,");
    // A single literal (a discriminator) stays a plain String.
    expect(s).toContain("    val type: String,");
  });

  it("builds a sealed interface from inline object variants", () => {
    const f = fixture(
      "disc.ts",
      `
      export type Agent = "claude-code" | "codex";
      /** How to build the process. */
      export type Spec =
        | { kind: "shell" }
        | { kind: "command"; command: string }
        | { kind: "agent"; agent: Agent; prompt?: string };
      `,
    );
    const { kotlin, warnings } = generateKotlin([f]);
    const e = block(kotlin, "Spec");
    expect(e).toContain("/** How to build the process. */");
    expect(e).toContain("@Serializable(with = Spec.Serializer::class)\nsealed interface Spec {");
    expect(e).toContain("    data object Shell : Spec\n");
    expect(e).toContain(
      "    @Serializable\n    data class Command(\n        val command: String,\n    ) : Spec",
    );
    expect(e).toContain("        val agent: Agent,");
    expect(e).toContain("        val prompt: String? = null,");
    expect(e).toContain("    data class Unknown(val raw: JsonElement) : Spec");
    expect(e).toContain(
      '    object Serializer : DiscriminatedUnionSerializer<Spec>("dev.optio.core.model.Spec", "kind") {',
    );
    expect(e).toContain('            "shell" -> Shell\n');
    expect(e).toContain(
      '            "command" -> json.decodeFromJsonElement(Command.serializer(), element.withoutDiscriminator())',
    );
    expect(e).toContain("            else -> null");
    expect(e).toContain('            is Shell -> tagged("shell")');
    expect(e).toContain(
      '            is Command -> tagged("command", json.encodeToJsonElement(Command.serializer(), value))',
    );
    expect(e).toContain("            is Unknown -> value.raw");
    expect(e).toContain("        override fun unknown(raw: JsonElement): Spec = Unknown(raw)");
    expect(kotlin).toContain("import kotlinx.serialization.json.JsonObject");
    expect(kotlin).toContain("import kotlinx.serialization.json.Json\n");
    expect(warnings).toEqual([]);
  });

  it("builds a sealed interface that named interfaces implement", () => {
    const f = fixture(
      "events.ts",
      `
      export type WsEvent = TaskLogEvent | TaskDoneEvent | PingEvent;
      export interface TaskLogEvent { type: "task:log"; taskId: string; content: string }
      export interface TaskDoneEvent { type: "task:done" | "task:acked"; taskId: string }
      export interface PingEvent { type: "ping" }
      `,
    );
    const { kotlin, warnings } = generateKotlin([f]);
    const e = block(kotlin, "WsEvent");
    expect(e).toContain(
      '"task:log" -> json.decodeFromJsonElement(TaskLogEvent.serializer(), element)',
    );
    expect(e).toContain(
      '"task:done", "task:acked" -> json.decodeFromJsonElement(TaskDoneEvent.serializer(), element)',
    );
    // Named variants already carry the discriminator, so encoding passes straight through.
    expect(e).toContain(
      "is TaskLogEvent -> json.encodeToJsonElement(TaskLogEvent.serializer(), value)",
    );
    expect(e).not.toContain('tagged("task:log"');
    expect(e).not.toContain("data class TaskLogEvent");
    const log = block(kotlin, "TaskLogEvent");
    expect(log).toContain("    val type: String,");
    expect(log.endsWith(") : WsEvent")).toBe(true);
    expect(block(kotlin, "TaskDoneEvent")).toContain(") : WsEvent {");
    expect(block(kotlin, "TaskDoneEvent")).toContain("    val type: TypeValue,");
    expect(block(kotlin, "PingEvent").endsWith(") : WsEvent")).toBe(true);
    expect(warnings).toEqual([]);
  });

  it("qualifies a nested union that named structs implement", () => {
    const f = fixture(
      "nestedunion.ts",
      `
      export interface Cat { kind: "cat"; lives: number }
      export interface Dog { kind: "dog"; good: boolean }
      export interface Holder { pet: Cat | Dog }
      `,
    );
    const { kotlin } = generateKotlin([f]);
    expect(block(kotlin, "Holder")).toContain(
      "    @Serializable(with = Pet.Serializer::class)\n    sealed interface Pet {",
    );
    expect(block(kotlin, "Cat").endsWith(") : Holder.Pet")).toBe(true);
    expect(block(kotlin, "Dog").endsWith(") : Holder.Pet")).toBe(true);
  });

  it("keeps variant classes clear of top-level names and the fallback", () => {
    const f = fixture(
      "variantnames.ts",
      `
      export interface Shared { id: string }
      export type Msg =
        | { type: "shared"; id: string }
        | { type: "unknown" }
        | { type: "string"; value: string };
      `,
    );
    const e = block(generateKotlin([f]).kotlin, "Msg");
    expect(e).toContain("    data class Shared2(");
    expect(e).toContain("    data object UnknownValue : Msg");
    expect(e).toContain("    data class StringValue(");
    expect(e).toContain('"unknown" -> UnknownValue');
  });

  it("falls back to JsonElement with a warning for irregular unions", () => {
    const f = fixture(
      "irregular.ts",
      `
      export type Mixed = string | { a: number };
      export type NoKey = { a: string } | { b: string };
      export interface Holder { pair: [string, number]; fn: () => void }
      `,
    );
    const { kotlin, warnings } = generateKotlin([f]);
    expect(block(kotlin, "Mixed")).toBe("typealias Mixed = JsonElement");
    expect(block(kotlin, "NoKey")).toBe("typealias NoKey = JsonElement");
    expect(block(kotlin, "Holder")).toContain("    val pair: JsonElement,");
    expect(block(kotlin, "Holder")).toContain("    val fn: JsonElement,");
    expect(warnings.filter((w) => w.includes("emitted as JsonElement"))).toHaveLength(4);
  });

  it("makes `Named | null` aliases nullable typealiases", () => {
    const f = fixture(
      "nullalias.ts",
      `
      export interface Inner { id: string }
      export type MaybeInner = Inner | null;
      export type Same = Inner;
      export type AlsoMaybe = MaybeInner;
      export interface Uses { a?: MaybeInner; b: Array<AlsoMaybe | null>; c: MaybeInner }
      `,
    );
    const { kotlin } = generateKotlin([f]);
    expect(block(kotlin, "MaybeInner")).toBe("typealias MaybeInner = Inner?");
    expect(block(kotlin, "Same")).toBe("typealias Same = Inner");
    // Already nullable: no redundant `?`.
    const uses = block(kotlin, "Uses");
    expect(uses).toContain("    val a: MaybeInner = null,");
    expect(uses).toContain("    val b: List<AlsoMaybe>,");
    expect(uses).toContain("    val c: MaybeInner,");
  });

  it("backticks Kotlin keywords and renames keys that are not identifiers", () => {
    const f = fixture(
      "keywords.ts",
      `
      export interface Kw {
        default: string;
        in: number;
        object?: string;
        is: boolean;
        "content-type": string;
      }
      `,
    );
    const { kotlin } = generateKotlin([f]);
    const s = block(kotlin, "Kw");
    // `default` is only a keyword in Swift.
    expect(s).toContain("    val default: String,");
    expect(s).toContain("    val `in`: Double,");
    expect(s).toContain("    val `object`: String? = null,");
    expect(s).toContain("    val `is`: Boolean,");
    expect(s).toContain('    @SerialName("content-type") val contentType: String,');
    expect(kotlin).toContain("import kotlinx.serialization.SerialName");
  });

  it("flattens `extends` and intersections, and nests inline object types", () => {
    const f = fixture(
      "extends.ts",
      `
      export interface Base { id: string; role: string }
      export interface WithUser extends Base { email: string; role: "admin" | "member" }
      export type Both = Base & { extra: boolean };
      export interface Outer {
        user?: { id: string; avatarUrl?: string };
        items: Array<{ path: string }>;
      }
      `,
    );
    const { kotlin, warnings } = generateKotlin([f]);
    const w = block(kotlin, "WithUser");
    expect(w).toContain("    val id: String,");
    expect(w).toContain("    val email: String,");
    // Child overrides the inherited field type but keeps its position.
    expect(w).toContain("    val role: Role,");
    expect(w.indexOf("val role")).toBeLessThan(w.indexOf("val email"));
    expect(w).toContain("    enum class Role(override val raw: String) : RawEnum {");
    const b = block(kotlin, "Both");
    expect(b).toContain("data class Both(");
    expect(b).toContain("    val extra: Boolean,");
    const o = block(kotlin, "Outer");
    expect(o).toContain("    @Serializable\n    data class User(");
    expect(o).toContain("    val user: User? = null,");
    expect(o).toContain("    data class Item(");
    expect(o).toContain("    val items: List<Item>,");
    expect(warnings).toEqual([]);
  });

  it("resolves `keyof typeof CONST` through the type checker", () => {
    const f = fixture(
      "keyof.ts",
      `
      export const PRESETS = { node: { tag: "n" }, base: { tag: "b" } } as const;
      export type PresetId = keyof typeof PRESETS;
      `,
    );
    const { kotlin, warnings } = generateKotlin([f]);
    const e = block(kotlin, "PresetId");
    expect(e).toContain("enum class PresetId(override val raw: String) : RawEnum {");
    expect(e).toContain('    BASE("base"),\n    NODE("node"),');
    expect(warnings).toEqual([]);
  });

  it("skips generics, classes, functions, consts and method-bearing interfaces", () => {
    const f = fixture(
      "skip.ts",
      `
      export interface Box<T> { value: T }
      export class Thing { x = 1 }
      export function go(): void {}
      export const N = 3;
      export interface Api { readonly kind: string; call(): void }
      export interface Holder { api?: Api }
      `,
    );
    const { kotlin, warnings } = generateKotlin([f]);
    expect(kotlin).not.toContain("Box");
    expect(kotlin).not.toContain("Thing");
    expect(kotlin).not.toContain("class Api");
    expect(block(kotlin, "Holder")).toContain("    val api: JsonElement? = null,");
    expect(
      warnings.some((w) => w.endsWith("skip.ts:Api: interface has method members; skipped")),
    ).toBe(true);
  });

  it("maps index-signature interfaces to maps and empty interfaces to data objects", () => {
    const f = fixture(
      "dict.ts",
      `
      export interface Config { [key: string]: unknown }
      export interface Env { [key: string]: string }
      /** Nothing to see. */
      export interface Empty {}
      `,
    );
    const { kotlin } = generateKotlin([f]);
    expect(block(kotlin, "Config")).toBe("typealias Config = Map<String, JsonElement>");
    expect(block(kotlin, "Env")).toBe("typealias Env = Map<String, String>");
    expect(block(kotlin, "Empty")).toBe("/** Nothing to see. */\n@Serializable\ndata object Empty");
  });

  it("prefixes colliding names across files and orders output by file name", () => {
    const a = fixture("zeta.ts", `export interface Shared { z: string }`);
    const b = fixture(
      "alpha.ts",
      `export interface Shared { a: string }\nexport interface First { x: string }`,
    );
    const { kotlin, warnings } = generateKotlin([a, b]);
    expect(kotlin.indexOf("// region alpha.ts")).toBeLessThan(kotlin.indexOf("// region zeta.ts"));
    expect(block(kotlin, "Shared")).toContain("    val a: String,");
    expect(block(kotlin, "ZetaShared")).toContain("    val z: String,");
    expect(warnings.some((w) => w.includes("collides") && w.includes("ZetaShared"))).toBe(true);
  });

  it("escapes string literals and defuses comment delimiters in docs", () => {
    const f = fixture(
      "escape.ts",
      `
      /** Globs like src/*.ts */
      export type Odd = "$money" | 'say "hi"' | "back\\\\slash"; // closes */ early
      `,
    );
    const e = block(generateKotlin([f]).kotlin, "Odd");
    expect(e).toContain('MONEY("\\$money"),');
    expect(e).toContain('SAY_HI("say \\"hi\\""),');
    expect(e).toContain('BACK_SLASH("back\\\\slash"),');
    // Kotlin block comments nest, so neither delimiter may survive inside KDoc.
    expect(e).toContain("/**\n * Globs like src/&#42;.ts\n * closes *&#47; early\n */");
  });

  it("degrades a numeric enum that does not fit an Int", () => {
    const f = fixture("ratio.ts", `export enum Ratio { Half = 0.5, Whole = 1 }`);
    const { kotlin, warnings } = generateKotlin([f]);
    expect(block(kotlin, "Ratio")).toBe("typealias Ratio = Double");
    expect(warnings.some((w) => w.includes("Ratio") && w.includes("does not fit an Int"))).toBe(
      true,
    );
  });

  it("honours its own skip-file pragma, not gen-swift's", () => {
    const kotlinOnly = fixture(
      "kskip.ts",
      `// gen-kotlin: skip-file\nexport interface HandWrittenInKotlin { a: string }`,
    );
    const swiftOnly = fixture(
      "sskip.ts",
      `// gen-swift: skip-file\nexport interface HandWrittenInSwift { a: string }`,
    );
    const { kotlin } = generateKotlin([kotlinOnly, swiftOnly]);
    expect(kotlin).not.toContain("HandWrittenInKotlin");
    expect(kotlin).toContain("data class HandWrittenInSwift(");
    const { swift } = generateSwift([kotlinOnly, swiftOnly]);
    expect(swift).toContain("public struct HandWrittenInKotlin");
    expect(swift).not.toContain("HandWrittenInSwift");
  });

  it("is deterministic", () => {
    const f = fixture("det.ts", `export interface A { a: string }\nexport type B = "x" | "y";`);
    expect(generateKotlin([f]).kotlin).toBe(generateKotlin([f]).kotlin);
  });
});

describe("Kotlin naming helpers", () => {
  it("upperSnake splits separators and camel humps", () => {
    expect(upperSnake("pending")).toBe("PENDING");
    expect(upperSnake("pr_opened")).toBe("PR_OPENED");
    expect(upperSnake("PR_OPENED")).toBe("PR_OPENED");
    expect(upperSnake("api-key")).toBe("API_KEY");
    expect(upperSnake("CHANGES_REQUESTED")).toBe("CHANGES_REQUESTED");
    expect(upperSnake("task:message_delivered")).toBe("TASK_MESSAGE_DELIVERED");
    expect(upperSnake("IfNotPresent")).toBe("IF_NOT_PRESENT");
    expect(upperSnake("CICheck")).toBe("CI_CHECK");
    expect(upperSnake("Low")).toBe("LOW");
    expect(upperSnake("123abc")).toBe("_123ABC");
    expect(upperSnake("")).toBe("EMPTY");
  });

  it("escapeKotlinIdent backticks hard keywords only", () => {
    expect(escapeKotlinIdent("in")).toBe("`in`");
    expect(escapeKotlinIdent("when")).toBe("`when`");
    expect(escapeKotlinIdent("default")).toBe("default");
    expect(escapeKotlinIdent("value")).toBe("value");
    expect(escapeKotlinIdent("taskId")).toBe("taskId");
  });
});

describe("reserved Kotlin type names", { timeout: PROGRAM_TIMEOUT_MS }, () => {
  it("prefixes names that shadow platform types, like gen-swift", () => {
    const { kotlin } = generateKotlin([
      fixture(
        "reserved.ts",
        `export interface Task { id: string }\nexport interface Ref { task: Task }\n` +
          `export interface Instant { at: string }\nexport interface Unknown { x: string }`,
      ),
    ]);
    expect(kotlin).toContain("data class OptioTask(");
    expect(block(kotlin, "Ref")).toContain("    val task: OptioTask,");
    expect(kotlin).not.toMatch(/data class Task\b/);
    // Kotlin-only: names the generated code or its support files already use.
    expect(kotlin).toContain("data class OptioInstant(");
    expect(kotlin).toContain("data class OptioUnknown(");
  });
});

describe("the shared front end", { timeout: PROGRAM_TIMEOUT_MS }, () => {
  it("hoists an alias's helper types even when they nest a same-named enum", () => {
    const f = fixture("hoist.ts", `export type Foo = Array<{ foo: "x" | "y" }>;`);
    const { kotlin } = generateKotlin([f]);
    expect(block(kotlin, "FooItem")).toContain("    enum class Foo(");
    expect(block(kotlin, "Foo")).toBe("typealias Foo = List<FooItem>");
    const { swift } = generateSwift([f]);
    expect(swift).toContain("public struct FooItem: Codable, Hashable, Sendable {");
    expect(swift).toContain("public typealias Foo = [FooItem]");
  });

  it("gives the real inputs the same top-level names in Swift and Kotlin", () => {
    const inputs = defaultInputs();
    const { kotlin, warnings } = generateKotlin(inputs);
    const { swift } = generateSwift(inputs);
    // glance.ts is hand-written on iOS (`gen-swift: skip-file`) and generated for Kotlin.
    const glance = generateKotlin(inputs.filter((f) => path.basename(f) === "glance.ts")).kotlin;
    const glanceNames = new Set(kotlinNames(glance));
    expect(glanceNames).toContain("WatchState");
    expect(glanceNames).toContain("WatchItem");
    expect(kotlinNames(kotlin).filter((n) => !glanceNames.has(n))).toEqual(swiftNames(swift));
    expect(kotlin).toContain("data class OptioTask(");
    expect(kotlin).toContain("sealed interface WsEvent {");
    expect(warnings).toHaveLength(7);
  });
});
