/**
 * gen-swift — emit Swift `Codable` models from the shared TypeScript protocol
 * types so the iOS app (apps/ios) and the server share one wire format.
 *
 *   pnpm --filter @optio/shared gen:swift      # writes apps/ios/Optio/Generated/SharedTypes.swift
 *
 * The TypeScript side is read by the shared front end in gen-model.ts (also
 * used by gen-kotlin.ts); this file only renders its declarations as Swift.
 *
 * Mapping (see docs at the top of the generated file for the Swift side):
 *   interface / object type alias   → public struct (Codable, Hashable, Sendable)
 *   string enum / string-literal union → String-raw enum with a `.unknown` fallback
 *   numeric enum                    → Int-raw enum
 *   discriminated object union      → enum with associated payload structs
 *   `X | null`, `x?: X`             → Optional
 *   unknown / any / functions / tuples / anything irregular → AnyCodable (+ warning)
 *
 * Generic types, classes, functions and consts are skipped silently. Interfaces
 * with method members are skipped with a warning (they are not data). A file
 * whose Swift twin is hand-written opts out with a leading
 * `// gen-swift: skip-file` comment.
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import {
  addWarning,
  buildModel,
  camelCase,
  defaultInputs,
  IDENT_RE,
  pascalCase,
  SHARED_RESERVED_NESTED_NAMES,
  SHARED_RESERVED_TYPE_NAMES,
  type Decl,
  type IntEnumDecl,
  type ModelOptions,
  type StringEnumDecl,
  type StructDecl,
  type TypeRef,
  type UnionDecl,
} from "./gen-model.js";

export { camelCase, defaultInputs, pascalCase };

export interface GenerateResult {
  swift: string;
  warnings: string[];
}

const HEADER = "// GENERATED by packages/shared/scripts/gen-swift.ts — do not edit.";

const ANY = "AnyCodable";
const UNKNOWN_RAW = "__unknown__";

/** Identifiers that must be backtick-escaped when used as Swift member names. */
const SWIFT_KEYWORDS = new Set([
  "default",
  "in",
  "operator",
  "protocol",
  "where",
  "import",
  "class",
  "struct",
  "enum",
  "func",
  "var",
  "let",
  "return",
  "self",
  "Self",
  "Type",
  "internal",
  "public",
  "private",
  "fileprivate",
  "open",
  "static",
  "throws",
  "rethrows",
  "throw",
  "try",
  "catch",
  "is",
  "as",
  "repeat",
  "defer",
  "guard",
  "init",
  "deinit",
  "switch",
  "case",
  "extension",
  "associatedtype",
  "subscript",
  "inout",
  "if",
  "else",
  "for",
  "while",
  "do",
  "break",
  "continue",
  "fallthrough",
  "true",
  "false",
  "nil",
  "super",
  "typealias",
  "Any",
  "Protocol",
  "precedencegroup",
  "actor",
]);

const SWIFT_MODEL_OPTIONS: ModelOptions = {
  tool: "gen-swift",
  // A file whose Swift twin is hand-written (e.g. ActivityKit content state
  // in apps/ios/Shared) opts out with a leading `// gen-swift: skip-file`.
  skipFilePragma: /^\s*\/\/\s*gen-swift:\s*skip-file/m,
  reservedTypeNames: SHARED_RESERVED_TYPE_NAMES,
  reservedNestedNames: SHARED_RESERVED_NESTED_NAMES,
  anyName: ANY,
  anyDictName: `[String: ${ANY}]`,
  union: {
    variantTypeName: (literal) => `${pascalCase(literal)}Payload`,
    nameBareVariants: false,
    scopeNames: [],
    avoidTopLevelNames: false,
  },
};

// ── Naming helpers ─────────────────────────────────────────────────────────

export function escapeIdent(name: string): string {
  return SWIFT_KEYWORDS.has(name) ? `\`${name}\`` : name;
}

function swiftString(s: string): string {
  return `"${s
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r")
    .replace(/\t/g, "\\t")}"`;
}

function indent(text: string, level = 1): string {
  const pad = "    ".repeat(level);
  return text
    .split("\n")
    .map((l) => (l.length ? pad + l : l))
    .join("\n");
}

function docLines(lines: string[]): string {
  return lines.length ? lines.map((l) => `/// ${l}`.trimEnd()).join("\n") + "\n" : "";
}

// ── Generator ──────────────────────────────────────────────────────────────

export function generateSwift(sourceFiles: string[]): GenerateResult {
  const model = buildModel(sourceFiles, SWIFT_MODEL_OPTIONS);
  const warnings = [...model.warnings];
  const warn = (msg: string) => addWarning(warnings, msg);

  function typeText(t: TypeRef): string {
    switch (t.k) {
      case "string":
        return "String";
      case "number":
        return "Double";
      case "boolean":
        return "Bool";
      case "date":
        return "Date";
      case "any":
        return ANY;
      case "array":
        return `[${typeText(t.element)}${t.optional ? "?" : ""}]`;
      case "map":
        return `[String: ${typeText(t.value)}${t.optional ? "?" : ""}]`;
      case "entry":
        return t.entry.typeName;
      case "nested":
        return t.name;
    }
  }

  function emitDecl(d: Decl): string {
    switch (d.kind) {
      case "struct":
        return emitStruct(d);
      case "stringEnum":
        return emitStringEnum(d);
      case "intEnum":
        return emitIntEnum(d);
      case "union":
        return emitUnionEnum(d);
      case "alias":
        return `${docLines(d.docs)}public typealias ${d.name} = ${typeText(d.type)}${d.optional ? "?" : ""}`;
    }
  }

  function emitStruct(d: StructDecl): string {
    const props = d.props.map((p) => ({ ...p, type: typeText(p.type) }));
    const parts: string[] = [];
    if (d.nested.length) parts.push(d.nested.map(emitDecl).join("\n\n"));

    if (props.length) {
      parts.push(
        props
          .map(
            (p) =>
              `${docLines(p.docs)}public let ${escapeIdent(p.name)}: ${p.type}${p.optional ? "?" : ""}`,
          )
          .join("\n"),
      );
      parts.push(
        [
          "private enum CodingKeys: String, CodingKey {",
          ...props.map((p) => `    case ${escapeIdent(p.name)} = ${swiftString(p.jsonName)}`),
          "}",
        ].join("\n"),
      );
      const params = props
        .map((p) => `${escapeIdent(p.name)}: ${p.type}${p.optional ? "? = nil" : ""}`)
        .join(", ");
      const header = `public init(${params}) {`;
      parts.push(
        [
          header.length > 96
            ? `public init(\n${indent(params.split(", ").join(",\n"))}\n) {`
            : header,
          ...props.map((p) => `    self.${escapeIdent(p.name)} = ${escapeIdent(p.name)}`),
          "}",
        ].join("\n"),
      );
    } else {
      parts.push("public init() {}");
    }

    return `${docLines(d.docs)}public struct ${d.name}: Codable, Hashable, Sendable {\n${indent(parts.join("\n\n"))}\n}`;
  }

  function emitStringEnum(d: StringEnumDecl): string {
    const used = new Set<string>(["unknown"]);
    const lines: string[] = [];
    const known: string[] = [];
    for (const c of d.cases) {
      const base = camelCase(c.source);
      let caseName = base;
      if (caseName === "unknown") {
        caseName = "unknownValue";
        warn(
          `${d.at}: raw value "${c.raw}" collides with the \`.unknown\` fallback; emitted as \`.unknownValue\``,
        );
      }
      let n = 2;
      while (used.has(caseName)) caseName = `${base}${n++}`;
      used.add(caseName);
      known.push(caseName);
      lines.push(`${docLines(c.docs)}case ${escapeIdent(caseName)} = ${swiftString(c.raw)}`);
    }
    lines.push(
      `/// Fallback for raw values this client does not know about yet.\ncase unknown = ${swiftString(UNKNOWN_RAW)}`,
    );
    const body = [
      lines.join("\n"),
      `public static let allCases: [${d.name}] = [${known.map((k) => `.${k}`).join(", ")}]`,
      [
        "public init(from decoder: any Decoder) throws {",
        "    let raw = try decoder.singleValueContainer().decode(String.self)",
        `    self = ${d.name}(rawValue: raw) ?? .unknown`,
        "}",
      ].join("\n"),
    ];
    return `${docLines(d.docs)}public enum ${d.name}: String, Codable, Hashable, Sendable, CaseIterable {\n${indent(body.join("\n\n"))}\n}`;
  }

  function emitIntEnum(d: IntEnumDecl): string {
    const used = new Set<string>();
    const lines: string[] = [];
    for (const c of d.cases) {
      const base = camelCase(c.source);
      let caseName = base;
      let n = 2;
      while (used.has(caseName)) caseName = `${base}${n++}`;
      used.add(caseName);
      lines.push(`${docLines(c.docs)}case ${escapeIdent(caseName)} = ${c.value}`);
    }
    return `${docLines(d.docs)}public enum ${d.name}: Int, Codable, Hashable, Sendable, CaseIterable {\n${indent(lines.join("\n"))}\n}`;
  }

  function emitUnionEnum(d: UnionDecl): string {
    const key = d.key;
    const seenCases = new Set<string>();
    const variants = d.variants.map((v) => {
      let caseName = camelCase(v.literals[0]);
      if (caseName === "unknown") caseName = "unknownValue";
      let n = 2;
      while (seenCases.has(caseName)) caseName = `${camelCase(v.literals[0])}${n++}`;
      seenCases.add(caseName);
      const p = v.payload;
      return {
        literals: v.literals,
        caseName,
        /** Swift type of the associated value, or null for a bare case. */
        payload: p.k === "entry" ? p.entry.typeName : p.k === "inline" ? p.struct.name : null,
        /** True when the payload struct already contains the discriminator field. */
        payloadHasDiscriminator: p.k === "entry",
      };
    });

    const cases: string[] = [];
    const payloadStructs: string[] = [];
    for (const [i, v] of variants.entries()) {
      const p = d.variants[i].payload;
      if (p.k === "inline") payloadStructs.push(emitStruct(p.struct));
      cases.push(
        v.payload
          ? `case ${escapeIdent(v.caseName)}(${v.payload})`
          : `case ${escapeIdent(v.caseName)}`,
      );
    }
    cases.push(
      `/// Fallback for discriminator values this client does not know about yet.\ncase unknown(${ANY})`,
    );

    const decodeLines = [
      "public init(from decoder: any Decoder) throws {",
      "    let container = try decoder.container(keyedBy: DiscriminatorKey.self)",
      `    let discriminator = try container.decodeIfPresent(String.self, forKey: .${escapeIdent(key)}) ?? ""`,
      "    switch discriminator {",
    ];
    for (const v of variants) {
      const pattern = v.literals.map(swiftString).join(", ");
      decodeLines.push(
        v.payload
          ? `    case ${pattern}: self = .${v.caseName}(try ${v.payload}(from: decoder))`
          : `    case ${pattern}: self = .${v.caseName}`,
      );
    }
    decodeLines.push(`    default: self = .unknown(try ${ANY}(from: decoder))`, "    }", "}");

    const encodeLines = [
      "public func encode(to encoder: any Encoder) throws {",
      "    switch self {",
    ];
    for (const v of variants) {
      if (v.payload && v.payloadHasDiscriminator) {
        encodeLines.push(
          `    case .${v.caseName}(let payload):`,
          "        try payload.encode(to: encoder)",
        );
      } else if (v.payload) {
        encodeLines.push(
          `    case .${v.caseName}(let payload):`,
          "        var container = encoder.container(keyedBy: DiscriminatorKey.self)",
          `        try container.encode(${swiftString(v.literals[0])}, forKey: .${escapeIdent(key)})`,
          "        try payload.encode(to: encoder)",
        );
      } else {
        encodeLines.push(
          `    case .${v.caseName}:`,
          "        var container = encoder.container(keyedBy: DiscriminatorKey.self)",
          `        try container.encode(${swiftString(v.literals[0])}, forKey: .${escapeIdent(key)})`,
        );
      }
    }
    encodeLines.push(
      "    case .unknown(let value):",
      "        try value.encode(to: encoder)",
      "    }",
      "}",
    );

    const rawKey = IDENT_RE.test(key)
      ? `case ${escapeIdent(key)}`
      : `case ${escapeIdent(camelCase(key))} = ${swiftString(key)}`;
    const body = [
      cases.join("\n"),
      ...payloadStructs,
      `private enum DiscriminatorKey: String, CodingKey {\n    ${rawKey}\n}`,
      decodeLines.join("\n"),
      encodeLines.join("\n"),
    ];
    return `${docLines(d.docs)}public enum ${d.name}: Codable, Hashable, Sendable {\n${indent(body.join("\n\n"))}\n}`;
  }

  // ── Emit ─────────────────────────────────────────────────────────────────

  const sections: string[] = [];
  let currentFile = "";
  for (const { entry, decls } of model.entries) {
    if (entry.file !== currentFile) {
      currentFile = entry.file;
      sections.push(`// MARK: - ${path.basename(entry.file)}`);
    }
    sections.push(decls.map(emitDecl).join("\n\n"));
  }

  const swift = [
    HEADER,
    "//",
    "// Source: packages/shared/src/types/*.ts (+ utils/extract-work-links.ts).",
    "// Regenerate with `pnpm gen:swift`. AnyCodable lives in AnyCodable.swift (hand-written).",
    "//",
    "// Conventions:",
    "//   • String enums carry a `.unknown` fallback so new server values never fail decoding.",
    "//   • Discriminated unions decode unrecognised variants into `.unknown(AnyCodable)`.",
    "//   • TypeScript `Date` fields are `Date`; configure your JSONDecoder's dateDecodingStrategy.",
    "//   • TypeScript `number` is `Double`.",
    "",
    "import Foundation",
    "",
    ...sections.flatMap((s) => [s, ""]),
  ].join("\n");

  return { swift, warnings };
}

// ── CLI ─────────────────────────────────────────────────────────────────────

export function defaultOutput(): string {
  const here = path.dirname(fileURLToPath(import.meta.url));
  return path.resolve(here, "../../../apps/ios/Optio/Generated/SharedTypes.swift");
}

function main(): void {
  const out = process.argv[2] ? path.resolve(process.argv[2]) : defaultOutput();
  const { swift, warnings } = generateSwift(defaultInputs());
  for (const w of warnings) console.error(`gen-swift: warn: ${w}`);
  fs.mkdirSync(path.dirname(out), { recursive: true });
  fs.writeFileSync(out, swift);
  console.error(
    `gen-swift: wrote ${path.relative(process.cwd(), out)} (${warnings.length} warning(s))`,
  );
}

if (process.argv[1] && pathToFileURL(path.resolve(process.argv[1])).href === import.meta.url) {
  main();
}
