-- Replay order for session chat history. Events carry the API's millisecond
-- clock, and one agent output chunk yields several (Session started, reply,
-- cost) in the same millisecond; with random UUID ids nothing broke the tie,
-- so a replay could read cost → reply → "Session started". `seq` is the
-- insertion order (the chat handler persists a socket's events in emission
-- order) and the tiebreaker after `timestamp`. Existing rows are numbered in
-- table order.
ALTER TABLE "session_chat_events" ADD COLUMN IF NOT EXISTS "seq" bigint GENERATED BY DEFAULT AS IDENTITY;
