package dev.optio.core.model

import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.KSerializer
import kotlinx.serialization.SerializationException
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonDecoder
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonEncoder
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.buildJsonObject

// Hand-written companion to SharedTypes.kt (generated by packages/shared/scripts/gen-kotlin.ts):
// the machinery behind the generated discriminated unions. Not regenerated.

/**
 * Base of the generated discriminated-union serializers (`WsEvent.Serializer`, …). It reads the
 * [discriminator] field and hands the object to the matching variant; anything it does not
 * recognise — an unknown or missing discriminator, or a value that is not a JSON object — becomes
 * the union's `Unknown(raw)` fallback instead of failing, like the iOS `.unknown(AnyCodable)`.
 * Encoding writes the discriminator back for variants whose class does not declare it. JSON only.
 */
abstract class DiscriminatedUnionSerializer<T : Any>(
    serialName: String,
    /** The discriminator property, e.g. `type` or `kind`. */
    val discriminator: String,
) : KSerializer<T> {
    @OptIn(ExperimentalSerializationApi::class)
    override val descriptor: SerialDescriptor =
        SerialDescriptor(serialName, JsonElement.serializer().descriptor)

    /** The variant for [tag] decoded from [element], or null when [tag] names no known variant. */
    protected abstract fun decode(tag: String, element: JsonObject, json: Json): T?

    /** [value] as JSON, discriminator included. */
    protected abstract fun encode(value: T, json: Json): JsonElement

    /** The `Unknown` fallback carrying [raw]. */
    protected abstract fun unknown(raw: JsonElement): T

    /** An object holding the discriminator [tag] followed by [payload]'s fields. */
    protected fun tagged(tag: String, payload: JsonElement? = null): JsonObject = buildJsonObject {
        put(discriminator, JsonPrimitive(tag))
        (payload as? JsonObject)?.forEach { (key, value) ->
            if (key != discriminator) put(key, value)
        }
    }

    /** This object minus the discriminator, for variant classes that do not declare it. */
    protected fun JsonObject.withoutDiscriminator(): JsonObject = JsonObject(this - discriminator)

    final override fun deserialize(decoder: Decoder): T {
        val input = decoder as? JsonDecoder
            ?: throw SerializationException("${descriptor.serialName} can only be decoded from JSON")
        val element = input.decodeJsonElement()
        val obj = element as? JsonObject ?: return unknown(element)
        val tag = (obj[discriminator] as? JsonPrimitive)?.takeIf { it.isString }?.content
            ?: return unknown(element)
        return decode(tag, obj, input.json) ?: unknown(element)
    }

    final override fun serialize(encoder: Encoder, value: T) {
        val output = encoder as? JsonEncoder
            ?: throw SerializationException("${descriptor.serialName} can only be encoded to JSON")
        output.encodeJsonElement(encode(value, output.json))
    }
}
