package dev.optio.core.model

import java.time.Instant
import java.time.OffsetDateTime
import java.time.ZoneOffset
import java.time.format.DateTimeFormatter
import java.time.format.DateTimeParseException
import java.time.temporal.ChronoUnit
import kotlin.math.floor
import kotlin.math.roundToLong
import kotlinx.serialization.KSerializer
import kotlinx.serialization.SerializationException
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import kotlinx.serialization.json.JsonDecoder
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.doubleOrNull

// Hand-written companion to SharedTypes.kt (generated by packages/shared/scripts/gen-kotlin.ts).
// Not regenerated.

/**
 * [Instant] the way the Optio API sends dates, with the rules of the iOS `APIClient.decodeDate`:
 * - a string: ISO-8601 with or without fractional seconds and with any UTC offset
 *   (`2026-09-22T16:37:00.123Z`, `2026-09-22T16:37:00Z`, `2026-09-22T18:37:00+02:00`);
 * - a number: epoch milliseconds when larger than 1e11, otherwise epoch seconds.
 *
 * Anything else fails decoding. Encodes like JavaScript's `Date.toISOString()` (UTC, millisecond
 * precision, e.g. `2026-09-22T16:37:00.123Z`), which every server route accepts.
 *
 * SharedTypes.kt applies it to every `Instant` through `@file:UseSerializers`; [OptioJson] also
 * registers it for `@Contextual Instant` properties in other modules.
 */
object FlexibleInstantSerializer : KSerializer<Instant> {
    override val descriptor: SerialDescriptor =
        PrimitiveSerialDescriptor("dev.optio.core.model.FlexibleInstant", PrimitiveKind.STRING)

    private val isoMillis: DateTimeFormatter =
        DateTimeFormatter.ofPattern("uuuu-MM-dd'T'HH:mm:ss.SSS'Z'").withZone(ZoneOffset.UTC)

    override fun serialize(encoder: Encoder, value: Instant) = encoder.encodeString(format(value))

    override fun deserialize(decoder: Decoder): Instant {
        if (decoder !is JsonDecoder) return parse(decoder.decodeString())
        val element = decoder.decodeJsonElement()
        val primitive = element as? JsonPrimitive
            ?: throw SerializationException("Expected a date, got $element")
        if (primitive.isString) return parse(primitive.content)
        val number = primitive.doubleOrNull
            ?: throw SerializationException("Expected a date, got $element")
        return fromEpoch(number)
    }

    /** An ISO-8601 date-time with an offset; throws [SerializationException] for anything else. */
    fun parse(text: String): Instant = try {
        OffsetDateTime.parse(text, DateTimeFormatter.ISO_OFFSET_DATE_TIME).toInstant()
    } catch (e: DateTimeParseException) {
        throw SerializationException("Unparseable date $text", e)
    }

    /** Epoch milliseconds when [value] is larger than 1e11, otherwise epoch seconds. */
    fun fromEpoch(value: Double): Instant {
        if (value > 1e11) {
            val millis = floor(value)
            val micros = ((value - millis) * 1_000).roundToLong()
            return Instant.ofEpochMilli(millis.toLong()).plusNanos(micros * 1_000)
        }
        val seconds = floor(value)
        val micros = ((value - seconds) * 1_000_000).roundToLong()
        return Instant.ofEpochSecond(seconds.toLong(), micros * 1_000)
    }

    /** [value] as `uuuu-MM-ddTHH:mm:ss.SSSZ` in UTC, like `Date.toISOString()`. */
    fun format(value: Instant): String = isoMillis.format(value.truncatedTo(ChronoUnit.MILLIS))
}
