package dev.optio.core.model

import kotlinx.serialization.KSerializer
import kotlinx.serialization.SerializationException
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

// Hand-written companion to SharedTypes.kt (generated by packages/shared/scripts/gen-kotlin.ts):
// the machinery behind the generated enums. Not regenerated.

/**
 * An enum generated from a TypeScript string enum or string-literal union. [raw] is the wire
 * value. Every such enum also has an `UNKNOWN` entry (raw `__unknown__`) that absorbs values this
 * client does not know yet, like the iOS `.unknown` case.
 */
interface RawEnum {
    /** The value on the wire. */
    val raw: String
}

/**
 * Serializer and lookup helpers for a [RawEnum]. Every generated string enum's companion object
 * extends this, so `TaskState.serializer()`, `TaskState.allCases` and `TaskState.fromRaw("…")`
 * all work. Values this client does not know decode to the `UNKNOWN` entry instead of throwing.
 */
abstract class RawEnumSerializer<E>(
    serialName: String,
    entries: List<E>,
    private val unknown: E,
) : KSerializer<E> where E : Enum<E>, E : RawEnum {
    private val byRaw: Map<String, E> = entries.associateBy { it.raw }

    /** Every entry this client knows: all but `UNKNOWN` (Swift's `allCases`). */
    val allCases: List<E> = entries.filter { it !== unknown }

    /** The entry for [raw], or `UNKNOWN` when this client does not know the value. */
    fun fromRaw(raw: String): E = byRaw[raw] ?: unknown

    /** The entry for [raw], or null when unknown (Swift's failable `init(rawValue:)`). */
    fun fromRawOrNull(raw: String): E? = byRaw[raw]

    override val descriptor: SerialDescriptor =
        PrimitiveSerialDescriptor(serialName, PrimitiveKind.STRING)

    override fun serialize(encoder: Encoder, value: E) = encoder.encodeString(value.raw)

    override fun deserialize(decoder: Decoder): E = fromRaw(decoder.decodeString())
}

/** An enum generated from a TypeScript numeric enum; [raw] is the wire value. */
interface RawIntEnum {
    /** The value on the wire. */
    val raw: Int
}

/**
 * Serializer and lookup helpers for a [RawIntEnum] (the companion object of every generated
 * numeric enum). Like Swift's Int-raw enums there is no unknown fallback: an unrecognised number
 * fails decoding.
 */
abstract class IntEnumSerializer<E>(
    serialName: String,
    entries: List<E>,
) : KSerializer<E> where E : Enum<E>, E : RawIntEnum {
    private val byRaw: Map<Int, E> = entries.associateBy { it.raw }

    /** Every entry. */
    val allCases: List<E> = entries.toList()

    /** The entry for [raw], or null when there is none. */
    fun fromRaw(raw: Int): E? = byRaw[raw]

    override val descriptor: SerialDescriptor =
        PrimitiveSerialDescriptor(serialName, PrimitiveKind.INT)

    override fun serialize(encoder: Encoder, value: E) = encoder.encodeInt(value.raw)

    override fun deserialize(decoder: Decoder): E {
        val raw = decoder.decodeInt()
        return byRaw[raw]
            ?: throw SerializationException("$raw is not a known ${descriptor.serialName} value")
    }
}
